### ISSUE TITLE
Add Use Global Settings option to Super Speedy Search widget

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#102]
If someone adds a widget, it lets them reconfigure everything, but they maybe already configured it from the Settings > Super Speedy Search area.

Can you please an option in the widget, below Search button text which is an HTML select.

Default option: Use Global Settings
2nd option: Custom Settings

If Global Settings is active, hide the remaining options from the widget panel.

If Custom Settings is active, show the remaining options.

In the code underneath, if Use Global Settings is active, then call the shortcode only with the placeholder text and the search button text.

https://i.imgur.com/6XJXJlL.png

**Comment by hmkayani** [comment]
This is implemented in version 4.47 and added in pull request 12 https://github.com/superspeedyplugins/super-speedy-search/pull/12

**Comment by dhilditch** [comment]
This looks great, added in final version 4.49
