### ISSUE TITLE
Add import/export area to SSF Advanced tab

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#105]
At the bottom of the advanced tab in SSF, add an export/import area with a single text box.

If the user clicks export, use ajax to serialize the fww_settings option and print that out in the single text box.

If the user clicks import, check if the box is empty, if it's not, ask them if they are sure and then deserialize whatever they have entered and if it deserializes successfully then save it to fww_settings. 

All of this is through the use of Ajax.

**Comment by voodoo911** [comment]
Implemented in 5.30

**Comment by dhilditch** [comment]
Confirmed fixed in 5.30
