### ISSUE TITLE
SSF: Filter by price should filter in price order

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#107]
**Describe the bug**
If you filter by price by setting a min and max price the results returned are a random assortment of items between those prices.

We need an option so that by default it sorts by price low to high or high to low. Or a button/dropdown to sort by price.

**To Reproduce**
Create a SSF price slider and enter a min and max value
See the items load and note they are not in a particular price order.

**Expected behavior**
Filter by price should return results in price order either low to high or hight to low.
OR
We need some filters/dropdown or button to sort by price in a super speedy way.

**Comment by thinkjarvisdesignandmarketing** [comment]
To add - The issue here is Scalability pro and auto infinite scroll encourages us to remove the default sort by price, random, rating, relevance, order dropdown that comes with WooCommerce.

If this is removed then there is no way to filter the prices by price order - Even when the price range is set in the filter.

**Comment by dhilditch** [comment]
@voodoo911 

1. Add new option to range filter to add ?orderby to urls, let users enter the default orderby text, e.g. price-asc
2. Test this works with the price filter which extends the range filter

**Comment by dhilditch** [comment]
Tested this and it has definitely been implemented.

![image](https://github.com/superspeedyplugins/issue-tracker/assets/3008613/6a3dd1e9-f56a-4409-9358-2a0a66d89f0e)
