### ISSUE TITLE
Add slug search to the back-end admin search and front-end search for searching terms and products and everything into SSS

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#108]
If a product is called 'Search engine services' but the slug is 'seo-services' it should be possible to search both front and backend using the slug 'seo services'.

Can  you please add an option to the main tab for the settings for this to let people enable it, have it enabled by default, and then alter the wp-admin product search, term search, wp_query search and front-end search (which also uses wp_query) to include searching the slugs if that option is enabled.

**Comment by hmkayani** [comment]
This is completed in v 4.48.  Pull Request number https://github.com/superspeedyplugins/super-speedy-search/pull/12

**Comment by dhilditch** [comment]
@hmkayani more work required here:

This is working for fulltext search and long tokens but it still needs more work. I am still merging the code and deploying including this outstanding bug.

1. Create a new product/post with a slug xx-yy-zz (all < 3 character tokens)
2. Set the name to something else e.g. Test 1
3. Search for xx-yy-zz

Nothing comes up because the fulltext search is all that happens here for post_name. We also need to include searching the postname in the like_queries.

I looked at the getSearchSQL and it *looks* like it's building the correct LIKE statement to search against post_name but you can run the test above and see that short tokens do not get found in the slug/post_name.

**Comment by hmkayani** [comment]
@dhilditch I tried all the combinations mentioned above and tried few other cases using less than 3 characters, but search results are displayed.

**Comment by dhilditch** [comment]
@hmkayani can you share what settings you used and what product slug and product name and what search?

It doesn't work for me with short tokens.

**Comment by hmkayani** [comment]
@dhilditch  https://www.loom.com/share/8434be0204dd4077a06a10dc54347de4?sid=057f3392-a61d-42ca-926b-88418c518015

**Comment by dhilditch** [comment]
@hmkayani I don't understand your video. I'm trying to close old bugs, but it looks like this one has no code attachd.

**Comment by dhilditch** [comment]
@hmkayani please don't make any more videos without commentary, it's not good for me.

Also - you can see in your video that your full page search works but not ajax search, so you've done something weird here given that ajax search uses the same code as full page search.

**Comment by hmkayani** [comment]
this one is already done and merged in main branch. issue 108 is already committed and you merged into main branch. so i believe we only need to close this issue. its already done.
![image](https://github.com/superspeedyplugins/issue-tracker/assets/32770138/a409b902-075a-45b9-a734-36b01cc20ec9)

**Comment by dhilditch** [comment]
Fixed in 4.49
