### ISSUE TITLE
SSF: Hide/disable this filter until other filters selected - feature, is not working in FSE

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#11]
**Describe the bug**
This feature is not working in FSE theme (GS for example). 
Whichever of the two options I choose, it doesn't work. (Hide/Disable).

The queries/loadingtime are the same.
The only way to reduce the queries here: https://fshome-19344.ove-ams.servebolt.cloud/category/pomola/
is by deactivating ssf

**Comment by dhilditch** [comment]
Are you able to use the Widget Context plugin to resolve this issue?

I added that piece of functionality to hide/show for certain terms etc, but the Widget Context plugin has way more functionality to give you comprehensive control over when these widgets appear:

https://wordpress.org/plugins/widget-context/

**Comment by gfarma** [comment]
I tried it, but it didn't work. I tried also visibility settings from Greenshift builder, same result.

**Comment by dhilditch** [comment]
Voodoo911, can you please reproduce this bug in your local on a full site editor (FSE) where our 'hide widget until' feature does not seem to be working. This one might be a toughy so if you have ANY questions at all please contact me through Discord. Glyn is setting up a private channel for us so we can discuss but also so Glyn can see our messages.

**Comment by voodoo911** [comment]
I'v tested  plugin with three different FSE themes, tried different widget configurations, but was unable to reproduce issue. SO if you can share more details or provide access, I will try to trace issue.

**Comment by gfarma** [comment]
First of all I would like to note that I am using FSE with visibility settings by GS plugin (the visibility settings are like this: display a block if custom meta is products 

![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/5850d39c-181b-4178-ad10-ed3dc27cc062)

and the same for subcategories to make the below navigation possible: 
When at a category are subcatgories diplay only the sub categories: https://staging.fshome.gr/category/mpanio/

when it has products, display only the products: https://staging.fshome.gr/category/mpanio/mpataries-mpaniou/mpataries-niptiros/

When I deactivate the SSF the query monitor goes from 1.88s to 1.15s at this category https://staging.fshome.gr/category/mpanio/

This was always like this: 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/94990ced-7683-4e04-808d-96e933cd840b)
???

**Comment by voodoo911** [comment]
Ok, so we have two separate problems:

**Comment by gfarma** [comment]
Yes of course, do you have an email to send you an admin invitation?

**Comment by dhilditch** [comment]
@gfarma he is evgen_85238 on Discord if you want to message him there, don't post access creds here.

**Comment by voodoo911** [comment]
We made tests on test site and @gfarma confirmed that hide/disable functionality work as required. 
Query issue - @gfarma will make separate ticket to trace query issue

**Comment by gfarma** [comment]
yes you can close the issue
