### ISSUE TITLE
SS Sitemaps - Generate Sitemap goes to a 404 page plugin doesnt work.

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#110]
**Describe the bug**
Super Speedy sitemaps doesnt work on the sites I have tested it on.

When you click generate sitemaps it goes to a 404 error page.

**To Reproduce**

1. install super speedy sitemaps
2.  disable sitemaps in yoast
3. click generate sitemap button in super speedy sitemaps
4. watch in horror as it takes you to a 404 error page (screenshot below:

![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/e00dd11a-c4ce-4d0f-8500-8fb4dc7a6d5a)

**Expected behavior**
The sitemap should generate

**Additional context**
I have tried this in my test environment and a live site so both root folder install and a site installed in a directory on the server. It doesnt make a difference. At the moment I cannot get this plugin to work at all.

**Comment by dhilditch** [comment]
Can you please test the following @thinkjarvisdesignandmarketing :

1. Visit wp-admin > Settings > Permalinks - hit SAVE
2. Flush your object cache
3. Try the sitemap again

**Comment by dhilditch** [comment]
Confirmed, if users do not see the sitemap, they need to visit Settings > Permalinks and hit save.

https://discord.com/channels/837258064704438282/1209821217624952895/1220356857491623967

**Comment by thinkjarvisdesignandmarketing** [comment]
Thanks @dhilditch sorry I've had a work experience placement student here this week so my time has been stretched while I've been providing training.

I'll try it again on one of my sites.
