### ISSUE TITLE
SSS Ajax does not work if WP Installed in subfolder

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#111]
1. Install WP to subfolder e.g. localhost/wordpress
2. Install super speedy search and build the tables
3. Try the ajax search

What happens: It doesn't work

What we want?: We want it to work.

Bear in mind our Ajax is not using wp-admin-ajax.php, it's using the REST API and then there is a must-use plugin for our ultra ajax which if enabled intercepts these requests.

I suspect the issue lies in the JS calling the wrong REST endpoints i.e. it's just calling /json/ rather than /wordpress/json/

Please investigate and fix the JS if that's where the issue lies.

**Comment by hmkayani** [comment]
It is implemented in branch name : techinn360-sss-ajax-subfolder-111 and readme version : 4.54

**Comment by dhilditch** [comment]
Final release version 4.60
