### ISSUE TITLE
Move SSS readiness status-affecting options to the top

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#115]
https://i.imgur.com/pJ5gGXT.png

Check the screenshot above.

When users install SSS, when they visit the Main tab, all the options from the main tab which affect the 'Readiness status' and if changed will require a table rebuild should be at the top underneath the Readiness status.

Please move them all up here.

**Comment by hmkayani** [comment]
It is implemented in branch name : techinn360-sss-readliness-status-115 and readme version : 4.53
