### ISSUE TITLE
Make SSS widget Gutenberg compatible

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#116]
We have a widget which some users use (many use our default overrides).

I want this widget to remain, but I additionally want a gutenberg block which uses the same codebase, i.e. it should render the same on the front end and then use our existing ajax calls (REST API or optionally overridden with our Ultra Ajax must-use plugin).

Basically - add a new gutenberg block which then renders our search form as it currently stands.

**Comment by hmkayani** [comment]
It is implemented in branch techinn360-116 and readme version : 4.56

**Comment by dhilditch** [comment]
fixed
