### ISSUE TITLE
Remove unused options from defines.php and move all used ones to Advanced tab of SSS

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#117]
I've used defines.php to create quick advanced options for various customers. I want these options to be available to others.

For each option in defines.php:

1. Check if it's still in use in the code, if it's not, delete it from defines.php
2. If it's in use, add an option to the advanced tab with whatever default is defined in defines.php then remove the definition from defines.php
3. If the define remains (e.g. if the user added their own define to wp-config.php) then the admin option should be disabled with a tooltip telling them this option has been overridden through their wp-config.php
4. When you're checking the option for the functionality throughout the code, it should continue to check if (defined('SSS_FAST_VISIBILITY_CHECK')) etc and so if the define exists then THAT should take priority and then if the define does not exist then use whatever setting is in the options. i.e. if a user has added a define to their wp-config.php, this update will change nothing for them, functionality will continue. For all other users, they will just see a new option in the advanced tab.

Please ensure you create a completely separate branch for this update.

**Comment by hmkayani** [comment]
It is implemented in branch techinn360-sss-remove-defines-117 and readme version : 4.53

**Comment by Glynnage** [comment]
1: There are still some options that are no longer in use, for example "Show Tax Descriptions". Please make sure to check for and delete options if they are no longer in the code. 
https://i.imgur.com/xc7RhU3.png
https://imgur.com/14UH66d

2: When an option is overridden in wp-config add a tooltip saying "This option has been overridden in wp-config.php" and also   grey out the text of whichever option is overridden: 
https://i.imgur.com/LHaHKTR.png
