### ISSUE TITLE
Move all defines.php options to Advanced tab of SSF

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#118]
I've used defines.php to create quick advanced options for various customers. I want these options to be available to others.

For each option in defines.php:

1. Check if it's still in use in the code, if it's not, delete it from defines.php
2. If it's in use, add an option to the advanced tab with whatever default is defined in defines.php then remove the definition from defines.php
3. If the define remains (e.g. if the user added their own define to wp-config.php) then the admin option should be disabled with a tooltip telling them this option has been overridden through their wp-config.php
4. When you're checking the option for the functionality throughout the code, it should continue to check if (defined('SSF_STOP_PAD_COUNTS')) etc and so if the define exists then THAT should take priority and then if the define does not exist then use whatever setting is in the options. i.e. if a user has added a define to their wp-config.php, this update will change nothing for them, functionality will continue. For all other users, they will just see a new option in the advanced tab.

Please ensure you create a completely separate branch for this update.

**Comment by voodoo911** [comment]
@dhilditch 
Questions: 
1. What will be naming of options? just liek SSF_RESET_INLINE_FILTERS , no need for textual explanation for any ?
2. How to set value for non boolean values? Like SSF_STOP_PAD_COUNTS ?

**Comment by dhilditch** [comment]
For each one, there normally will be a comment in the changelog. You can find the changelogs here: https://www.superspeedyplugins.com/kb/ or just search through the readme.txt file in the particular repo which is the source for the changelog. For some there are comments in the defines.php. Some have no info - so just add a list of those to this bug and I will give you the description.

e.g. SSF_RESET_INLINE_FILTERS  should be called Reset Inline Filters and if you search the readme.txt for that you find a usable comment: https://i.imgur.com/qtNQlpI.png where you would use: Changes the inline filters to reset...

For items which are arrays, there should be an html select2 populated with the options pulled from wordpress (e.g. pad_counts is per taxonomy) and then the ability to add multiple options and then have these options saved as an array, however you wish to implement that - please do it well as this little pattern of code will be repeated throughout our admin interfaces in future.

The vast majority are true/false checkboxes, some are text - e.g. SSF_DEFAULT_TEMPLATE - but we can't have people typing what they like and breaking things or loading arbitrary code and that option is almost completely eliminated now so ignore that one.

**Comment by voodoo911** [comment]
@dhilditch 
SSF_POLYLANG
SSF_ROLLUP_VARIATIONS
SSF_SHOP_AS_HOME_TEMPLATE_OVERRIDE
SSF_GET_TERM_SLUGS_THROUGH_FUNCTION
SSF_USE_SPRO_TRANSIENT_WIDGET_CACHE

Also:
define('SSF_STOP_PAD_COUNTS', array('product_cat'));  - its only array I see. What other options I sould add there?

Single textual:
 define('SSF_DEFAULT_TEMPLATE', 'archive-product.php');  - should it be ignored in settings?

**Comment by dhilditch** [comment]
I told you in last comment, ignore SSF_DEFAULT_TEMPLATE, but yes configure for SSF_STOP_PAD_COUNTS - also covered in the last comment

**Comment by dhilditch** [comment]
This part re: SSF_STOP_PAD_COUNTS:

_For items which are arrays, there should be an html select2 populated with the options pulled from wordpress (e.g. pad_counts is per taxonomy) and then the ability to add multiple options and then have these options saved as an array, however you wish to implement that - please do it well as this little pattern of code will be repeated throughout our admin interfaces in future._

**Comment by voodoo911** [comment]
I'm not really sure  what does it mean:
" (e.g. pad_counts is per taxonomy)" - what possible options we can have there?

**Comment by dhilditch** [comment]
All the taxonomies

**Comment by dhilditch** [comment]
(all the taxonomies for products currently, but really it's all the taxonomies because we will upgrade this to be filters for all post types in the future)

**Comment by dhilditch** [comment]
SSF_POLYLANG - enable this if you are using polylang.
SSF_ROLLUP_VARIATIONS - experimental: if you are using one of the show single variations plugins, enabling this option can help.
SSF_SHOP_AS_HOME_TEMPLATE_OVERRIDE - if your shop page is your home page but you don't use the regular shop template (archive-product.php) then enabling this can help.
SSF_GET_TERM_SLUGS_THROUGH_FUNCTION - enable to use WP functions to get term slugs, or disable for more speed if you are sure the slugs are not altered by filters
SSF_USE_SPRO_TRANSIENT_WIDGET_CACHE - enable this to use the scalability pro db transient cache rather than file based cache
