### ISSUE TITLE
Scalability pro add next page - previous page on products

### ISSUE THREAD

**Issue by ned-bs** [superspeedyplugins/issue-tracker#122]
**Remove SQL_CALC_ROWS remove pagination on admin page**

"When WP_Query fetches posts/products, it also calculates the total number of matching items. This is useful to display at the top of your shop/page/edit.php, e.g. Showing 1 - 50 of 650,000. However, this count requires either an index scan or table scan. Removing it, can result in ultra-fast WP_Query speed. Depending on your setup, you may need to switch to the natural sort order above too for successful use of the indexes. Since most users only need to view page 1, this is a recommended option but you should be aware that page counts will be incorrect as a result. Because of this, most people combine this option with an infinite scroll plugin."

**Also on edit.php, SQL_CALC_ROWS is used. If you remove it, you remove pagination on these pages, but searching is unaffected and your pages will load far faster.**

**Describe the solution you'd like**
It make admin panel fast but also remove functionality.
What if add next page and previous page links on top of wp-admin products page.
/wp-admin/edit.php?post_type=product
It can help to move next page, even there is no next page it is harmless

**Comment by ned-bs** [comment]
@voodoo911 I didn't understand what do you mean.
1. We use generatepress theme.
2. When SPRO removes pagination, we are not able to click somewhere to reach 2nd or 3rd page at backend.
But when I add page number to URL by hand, that works.

In this case;
Go to woocommerce products page (Or post, which I don't need) and add 2 buttons with next and previous page links.
1. Define a Page Number variable. 0 by default.
2. Put next page link ($pagenumber+1)
3. Put previous page link  ($pagenumber-1).

I guess, code should be something like this

`<?php
/*
Plugin Name: Custom Admin Pagination for WooCommerce
Description: Adds custom next and previous page buttons to the WooCommerce Products admin page.
*/

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

add_action('admin_footer', 'custom_pagination_buttons');

function custom_pagination_buttons() {
    global $pagenow;

    if ( 'edit.php' !== $pagenow || 'product' !== $_GET['post_type'] ) {
        return; // Only run on the products admin page.
    }

    // Determine the current page.
    $page = isset($_GET['paged']) ? absint($_GET['paged']) : 1;

    // Generate the URLs for the previous and next pages.
    $prev_link = add_query_arg('paged', max(1, $page - 1));
    $next_link = add_query_arg('paged', $page + 1);

    // Button styles and scripts
    echo "<style>.custom-pagination { padding: 5px 10px; margin: 5px; }</style>";
    
    // Output the buttons
    echo '<div style="padding: 20px 0;">';
    if ($page > 1) {
        echo '<a href="' . esc_url($prev_link) . '" class="button custom-pagination">Previous Page</a>';
    }
    echo '<a href="' . esc_url($next_link) . '" class="button custom-pagination">Next Page</a>';
    echo '</div>';
}

`

**Comment by dhilditch** [comment]
@voodoo911 - 

When scalability pro remove admin SQL CALC ROWS is enabled, pagination on wp-admin > products or wp-admin orders etc is broken.

When that option is enabled, simply add a NEXT PAGE and PREVIOUS page button where the pagination used to be.

**Comment by voodoo911** [comment]
@dhilditch 
Wrote you request about issue with pagination set

**Comment by ned-bs** [comment]
Hi, any plan?

**Comment by voodoo911** [comment]
@ned-bs Fix already applied

**Comment by ned-bs** [comment]
I am on 5.53 and woocommerce 8.9.0, I don't see anything like next page or previous page on products page.

**Comment by voodoo911** [comment]
![image](https://github.com/superspeedyplugins/issue-tracker/assets/33031060/a8098c26-6b05-44ab-90d3-903f60ca0341)
@dhilditch seems fix not merged yet?

**Comment by dhilditch** [comment]
Fixed in 5.55

**Comment by betayazilim** [comment]
Suggest to add it to media page too.
/wp-admin/upload.php page
