### ISSUE TITLE
Add orderby option to settings page of SSS and add apply_filters for sort order to both SSS and SSF

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#13]
Super Speedy Search defaults to ordering by RELEVANCE.

2 users have now asked for an option to enable their own sorting. I am not a fan, but I can understand when some people wish to search and then order by date.

1. Add an option to change the default sort order.
2. Ensure if the sort order is in the URL that it is obeyed.

Super Speedy Filters also has hard-coded sorting - i.e. if the user has created their own sorting, we need to take account of that.

https://discord.com/channels/837258064704438282/877862826528620554/1178782413745303714

@maguati has highlighted that if we create a simple filter for the sort order arguments then they would be able to hook into there rather than altering our code.

**Comment by thinkjarvisdesignandmarketing** [comment]
Yes please Dave,

I have a couple of customers in this situation as well.

**Comment by dhilditch** [comment]
1. Add new default sort order option, defaulted to RELEVANCE, to Settings > Super Speedy Search first tab
2. Adjust code in pre_get_posts to check the default sort order option and pass this through in the query vars so the query gets sorted by whatever the user asked for
3. Additionally, in pre_get_posts, if there is a sort order in the URL, e.g. against ?orderby=date&order=desc then ensure this sort order is used.

Super Speedy Search uses a clone of wp_posts which is identical except for extra columns to make the text search fast. That means any code which needs to join somewhere else to complete the sorting can happen, BUT these joins will cause slowdown so please come talk to me on Discord if you need more help understanding this.

**Comment by dhilditch** [comment]
The default orderby option has been added in 4.37 and it also obeys any change in the orderby dropdown from the results page, if your theme provides one.

Please note some ordering options will hurt performance so I highly recommend you keep EXACT search enabled.
