### ISSUE TITLE
Woocommerce Paypal Payments (official) and SPRO Cache Author Counts conflict - the link you followed has expired

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#131]
With WooCommerce PayPal Payments installed and SPRO Cache Author Counts option enabled:

1. Try to change Woo Order statuses using bulk actions

Expected: Order statuses change
What actually happens: The link you followed has expired page appears

I would like to find out at which point and WHY this happens. I presume Woo does some counting of author stats per status or similar and then raises an error when the counts don't update (because of our cache intercepting).

Please investigate and try and figure out a solution. Ideally we keep the author counts on bulk updates, but if we have to we could disable this functionality until after the bulk updates are complete.

https://discord.com/channels/837258064704438282/880089099074170942/1230813932353093672

**Comment by voodoo911** [comment]
@dhilditch based on description it look like same issue as https://github.com/superspeedyplugins/issue-tracker/issues/134 ? Can you pls confirm ?

**Comment by dhilditch** [comment]
@voodoo911 Indeed, related. The easiest repro is through the bulk edit.

First, I would like to uncover WHY it kills bulk edit, so please check that with debug log and breakpoints etc.

Second, if possible to fix so it works then fix that way.

Otherwise, we need some conditions added to the option so that it doesn't operate under these circumstances - bulk edit, or this woo paypal payments.

It would be far better if you could figure out a generic fix for this after figuring out the reason for the failure.

**Comment by dhilditch** [comment]
I see you added a commit for the function display_tablenav - was this function missing then?

You should see in my implementation that a hash is created of the underlying function so that the functionality is supposed to be disabled if the official class every changes.

**Comment by voodoo911** [comment]
Problem was that class create not correct nonce name, that's why WordPress was unable to verify it and provide error.

**Comment by voodoo911** [comment]
https://github.com/superspeedyplugins/issue-tracker/issues/131#issuecomment-2102818565

**Comment by dhilditch** [comment]
This looks to be fixed in 5.55 - please re-open this issue if it is not fixed properly for you.
