### ISSUE TITLE
Woodmart theme upload button dont work

### ISSUE THREAD

**Issue by datatime-sk** [superspeedyplugins/issue-tracker#132]
**Describe the bug**
I'm using the Woodmart theme. In the theme settings, it's not possible to upload images when the External Images plugin is enabled. When the External Images plugin is active and I go to the theme settings, I see this error in the console, which doesn't appear when the External Images plugin is disabled:

media-audiovideo.min.js?ver=6.5.2:2 
 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at media-audiovideo.min…s?ver=6.5.2:2:10579
    at media-audiovideo.min…s?ver=6.5.2:2:12021
(anonymous)	@	media-audiovideo.min.js?ver=6.5.2:2
(anonymous)	@	media-audiovideo.min.js?ver=6.5.2:2

When I click on any UPLOAD button in the theme settings (for example, in Page Title background), the following error appears in the console:

media-views.min.js?ver=6.5.2:2  Uncaught TypeError: Cannot read properties of undefined (reading 'limitExceeded')
    at n.initialize (media-views.min.js?ver=6.5.2:2:79926)
    at n.initialize (media-views.min.js?ver=6.5.2:2:73270)
    at h.View (backbone.min.js?ver=1.5.0:2:14872)
    at n.constructor (wp-backbone.min.js?ver=6.5.2:2:2602)
    at n.constructor (media-views.min.js?ver=6.5.2:2:106544)
    at n [as constructor] (backbone.min.js?ver=1.5.0:2:23777)
    at n [as constructor] (backbone.min.js?ver=1.5.0:2:23777)
    at new n (backbone.min.js?ver=1.5.0:2:23777)
    at wp.media (media-models.min.js?ver=6.5.2:2:11846)
    at HTMLButtonElement.<anonymous> (options.js?ver=7.5.1:612:32)
initialize @ media-views.min.js?ver=6.5.2:2
initialize @ media-views.min.js?ver=6.5.2:2
h.View @ backbone.min.js?ver=1.5.0:2
constructor @ wp-backbone.min.js?ver=6.5.2:2
constructor @ media-views.min.js?ver=6.5.2:2
n @ backbone.min.js?ver=1.5.0:2
n @ backbone.min.js?ver=1.5.0:2
n @ backbone.min.js?ver=1.5.0:2
wp.media @ media-models.min.js?ver=6.5.2:2
(anonymous) @ options.js?ver=7.5.1:612
dispatch @ load-scripts.php?c=1&load%5Bchunk_0%5D=wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks,jquery-core,jquery-migrate,utils&ver=6.5.2:7
v.handle @ load-scripts.php?c=1&load%5Bchunk_0%5D=wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks,jquery-core,jquery-migrate,utils&ver=6.5.2:7

**Screenshots**
<img width="1276" alt="image" src="https://github.com/superspeedyplugins/issue-tracker/assets/64972302/e57a7bd4-9dd4-4754-b167-8d8b1492f34d">

![image](https://github.com/superspeedyplugins/issue-tracker/assets/64972302/fc5fc6a3-9755-4f05-a230-67d0341f2e95)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 124.0.6367.61 / Edge 124.0.2478.51

Thank you

**Comment by hmkayani** [comment]
@dhilditch commited the code .. please check error is fixed .

**Comment by dhilditch** [comment]
Confirmed fixed in 3.15, deployment coming
