### ISSUE TITLE
Conflicts checker in SSF URL tab currently only checks page name conflicts

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#133]
If people choose to remove /product-category/ from their URLs, we have some code on the URL tab to check for them if conflicts exist.

This code only checks if any term slugs conflict with page slugs, but it should also check if there are conflicts with ANY OTHER term slugs and report them in the conflict area so people know they cannot remove the /product-category/ part from the URL until they resolve those conflicts.

**Comment by voodoo911** [comment]
@dhilditch "ANY OTHER term slugs"  - from product_cat taxonomy ?
As I understand from code right now we take all slugs from product_cat and check if there is any conflict with existed pages.
But not sure how to check conflict inside same terms? I mean what is logic of conflict?
