### ISSUE TITLE
New Author Post Cache stops bulk edit working - Link Expired

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#134]
**Describe the bug**
When The New Author Count Cache is enabled - Bulk actions are not working when trying to bulk edit orders and change the status to complete from the Orders > All Orders screen.

![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/d63829a6-2814-4607-95a8-26b1f6e9a43b)

**To Reproduce**
1. Enable Author Count Cache
2. Go to orders screen
3. Tick at least one order
4. Click mark as complete and apply
5. Watch as the message above appears

**Expected behavior**
Bulk edit orders should work

**Additional context**
Note I tried deleting %spro_posts_list_table_hash_version% from WP_options and regenerating this and it still doesnt resolve the issue.

**Comment by dhilditch** [comment]
Fixed in 5.55
