### ISSUE TITLE
SSF is adding ?expand_tax_name even when only 1 term selected

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#140]
https://discord.com/channels/837258064704438282/877862826528620554/1238511899088257105

If only 1 term is active in the URL for the filters, there's no need to add ?expand_tax_name

Fix the code so that if only 1 term active, we never care about expand/narrow because they are identical.

1. Create a multiselect expand filter
2. Select 1 item
3. Check if ?expand is there or not, it should not be
4. Possibly might have to select 2 items and then deselect 1 item to reproduce.

**Comment by thinkjarvisdesignandmarketing** [comment]
Hi Dave,

The issue also occurs when you set multi-select to NO or Expand.

It has caused all categories to be no index because of the query string.

**Comment by dhilditch** [comment]
Fixed in 5.58

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch

This appears to be fixed. After the next SEO audit from Screaming frog comes back I'll update you on a couple of other issues.

We are having some problems with Auto Infinite Scroll and SEO as well.
