### ISSUE TITLE
Scalability Pro breaks Elementor editor on editing just-created template

### ISSUE THREAD

**Issue by wpshushu** [superspeedyplugins/issue-tracker#143]
How to reproduce the issue:

1. Activate Elementor Pro , activate Scalability Pro 5.52
2. Start a new Elementor container template from WP-Admin => Templates => Saved Templatees => ADD NEW TEMPLATE 
3. Elementor editor opens up and fails at this error: https://www.screencast.com/t/eibcMypBx
4. Disable Scalability Pro, reload Elementor editor, it loads fine

Issue doesn't occur when editing existing Elementor templates, only occurs on just-created ones.

Here are component versions, although I don't think they matter. 

WP version: 6.4.4
Elementor pro version: 3.21.2
Scalability Pro version: 5.52

**Comment by dhilditch** [comment]
@wpshushu this sounds like this would be fixed if you changed the visibility option in SPRO. The one that hides private items. That is probably the conflict here. If so, please confirm in this bug so I can add info to our plugin and extra warnings about possible side-effects.

**Comment by wpshushu** [comment]
@dhilditch You're right. Switching off "hides private items" fixed the issue. Is there a way to programmatically enable/disable this option?

**Comment by dhilditch** [comment]
1. activate spro, set the 'disable private items' option
2. activate elementor
3. create a new elementor template

our hiding of private options in spro is breaking this 'draft' template.

Also test this:

1. As above
2. Create new post but do not publish
3. Click preview

I'm guessing that also breaks, so please fix both of these. I want this to be a generic solution that works for other 'previews' etc, so maybe the solution here is to avoid running our optimisation if is_single() is true.

**Comment by wpshushu** [comment]
Hi, what's the status of this ticket? If there isn't a fix soon, can I use a filter HOOK to turn off private checkout conditionally. 

Thanks

**Comment by dhilditch** [comment]
Sorry about the delay on this one. I've taken some time to think about how to redesign this alteration.

You can see how this is going to behave in this feature request:

https://github.com/superspeedyplugins/issue-tracker/issues/173

So basically, everything currently configured in the Archive tab will become global options which can be set to whatever is safe, and then you can override on specific hooks to start and end a particular WP_Query alteration.

This will fix this issue for you so you can ensure whatever hook you have gets to see the private items.
