### ISSUE TITLE
Add noindex (but follow) option to SSF in addition to our noindex options and rename the 'data-canonical

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#144]
A customer is paying to have these items expedited, so please let me know how many hours you spent on this task in Discord.

There are two items they are asking for, the first is fairly trivial:

https://imgur.com/z26jZmi

In the SSF Tax widget code, we use the word 'canonical' on our links to represent the link with this term selected. This is then used by our JavaScript code to highlight which items are selected.

Their SEO audits are flagging up issues here because of my use of the word canonical, so just rename this attribute to something else - data-term-link or something should be suitable.

You will need to update in the class-ssf-widget.php everywhere that sets canonical= to use the new name and then update the JS to reflect this and update the version number for the JS file in the main SSF file.

The 2nd item is a bit more complex around SEO behaviour. They want to be able to set some items to noindex+follow whereas currently we only allow noindex+nofollow or index+follow (they are currently called just noindex/follow)

So - we need an extra option here and then all the code that adds rel=nofollow needs to be updated so that rel=nofollow does not get added for the new noindex+follow option and all the code that adds the meta noindex tags to also be updated to obey the new option so that when followed google then knows not to index this page.

Here's his original request. Please create a branch specifically for this feature request.

Give me the ability to choose to have noindex some terms but follow in order to help Google to search deeper to our site. https://capture.dropbox.com/El6RzJrR8QyJBkGF I can imagine a dropdown next to the number field with 2 options noindex, nofollow and noindex, follow something like this https://capture.dropbox.com/F59OrSav1nrs8htk untill now I am overriding you on the file seo-handler.php on lines 347 and 353.
Please remove the canonical attribute from the filering widgets change this name with something else like data-url because SEO expert said me all the time that is something we have to tweak. I know you are using this attribute only to know which is the current chosen filter

**Comment by thinkjarvisdesignandmarketing** [comment]
Related
https://github.com/superspeedyplugins/issue-tracker/issues/141
https://github.com/superspeedyplugins/issue-tracker/issues/142

@dhilditch @voodoo911 
I think the issues above are related to this. Please take a look at Issue 142 in conjunction with this ticket - You mentioned changing the Canonical tag in the post. Although I have not been part of the discussion on Discord around this issue it would be worth confirming if the issue in 142 helps aleviate the issues raised here.

I hope this helps if not please ignore.
