### ISSUE TITLE
SSS | up to version 4.18 the SKU search is working correctly, above this version is not working

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#15]
**Describe the bug**
up to version 4.18 the SKU search is working correctly, above this version is not working

**Comment by gfarma** [comment]
It is fixed, you can close it

**Comment by dhilditch** [comment]
Confirmed by developer and by gfarma that this is an incorrectly reported issue.

**Comment by gfarma** [comment]
Dave I still got the issue would you like to test it at my staging?
