### ISSUE TITLE
/?expand_product_cat=1 added to all category filters when allow multi select is set to default - Major SEO problem - SSF

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#158]
**PLEASE COMPLETE ALL STEPS TO SPEED UP BUG FIXES**

1. Create some SSF widgets
2. Set respect other filters to yes
3. Set the allow multi select to default
4. Front the front end of the site when you select any of the categories from the widget /?expand_product_cat=1 gets added by default.
5. However when you select Expand product categories from Multi select it does not display /?expand_product_cat=1
6. You would expect this to be the other way around
7. The /?expand_product_cat=1 query string does not apply to every single category depth either.
8. Query strings are not followed by Google. This is causing an SEO problem
9. The query string should not be necessary as the categories exist so no need for query string
**10. Please can the default setting in allow multi select display without query strings**

Tell us what you have tried so far.
Changing allow multi select to yes, expand results removes the query string. The problem is I have over 100 widgets accross the site. Id need to change every single widget to expand results to fix the problem - I am trying to avoid this situation.

Image showing the issue on a single category where allow multi-select is set to default.
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/cb28c01a-8f48-4fcb-8cec-0315469a0158)

**Comment by dhilditch** [comment]
@thinkjarvisdesignandmarketing can you please test visiting settings > ssf > advanced and hit the clear cache button then report back?

I just checked and the fix is still in the code:

![image](https://github.com/superspeedyplugins/issue-tracker/assets/3008613/e0f2f715-9921-43e5-9dbd-77091c744dea)

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
This has suddenly started working properly again.
Not sure what happened here. I had cleared redis, ssf cache and wp-rocket several times.

Sorry about this I'll close the issue.
