### ISSUE TITLE
'Show search box' doesn't works correctly when you delte the value at the input | SSF

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#166]
At the SSF when you enable the option 'Show search box' -> Show

Then at the frontend if you type something at the box and you delete the text you just typed then it doesn;t return the filters.

1)
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/10728689-f8ea-45b7-ac5a-2ac37ec69caa)

2)
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/47f182a5-d780-4129-a0a1-472aaf12f718)

3)
I deleted the text
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/1d16718b-bef2-4149-84c2-0c0d41ab5fce)
no results

**Comment by dhilditch** [comment]
Fixed in last update, this was if you did CTRL+BACKSPACE
