### ISSUE TITLE
Clear button for search panel not working on search results page for Super Speedy Search

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#178]
1. Perform a search with super speedy search and hit enter
2. On the search results page, you'll see the box populated with your previous search
3. Click the x button to clear the box

What happens: Nothing
Expected: The box should become empty.

It looks like the clear button is trying to revert back to the default text on the page - e.g. if I search 'test' then on the search results page I change the search box text to 'test search' and then hit x then the box changes back to just 'test'

**Comment by hmkayani** [comment]
This has been implemented in branch https://github.com/superspeedyplugins/super-speedy-search/tree/178-clear-button-for-search-panel-not-working-on-search-results-page-for-super-speedy-search
pull request : https://github.com/superspeedyplugins/super-speedy-search/pull/35
readme version : 4.78

**Comment by dhilditch** [comment]
I'd actually taken you off this task as it was taking too long and it's implemented by me.

**Comment by dhilditch** [comment]
Fixed in 4.78
