### ISSUE TITLE
Short token multiplier not working for super speedy search

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#179]
![image](https://github.com/user-attachments/assets/81c6be73-1477-46a7-8bb7-cf1d0c1b2d4f)

Here you can see that variable is completely unused.

And then if I change the weight in my defines.php or if I edit it in wp-config.php, the weights do not change.

![image](https://github.com/user-attachments/assets/12316fe5-aff9-426a-bcb2-85735b73cae4)

1. Review the code you wrote before
2. Figure out why the short token multiplier is not being used
3. Fix it
4. Also ensure you add the short token weight output to the list of weights and to the output weight total

![image](https://github.com/user-attachments/assets/f588cfea-0190-4bca-b778-06e5988ea5d9)

**Comment by hmkayani** [comment]
@dhilditch I have checked this issue, the variable was added in "4.47" and is used when the search string is less than 3 characters which uses like queries. For that short token multiplier is working and being used with "title" only.
What I needed to ask If this is the correct working or the short token multiplier has to be added to "Like" queries or to all generally ?

**Comment by dhilditch** [comment]
It should be used when any individual token is less than 3 characters, not just the search string. It's fine for it to be working with the title only. The short token weight should probably increase the score of everything matched with the like LIKE operators.

e.g. if someone searches wi-fi 6 - there are 3 short tokens here, wi, fi and 6, so the short token weight should be added to the score 3 times. There will be some bad matches because of this e.g. it would also boost the score of "window finish 6" if that existed as a thing, and I'll have an advanced tutorial for people typically affected by this to reduce the minimum token length of mysql from 3 to 2 and rebuild their full text index.

When it comes to single tokens, those tend to be numbers and more accurate as matches, so that's the ultimate ideal for users of my tool - to use this short token weight to increase the score of matched single character tokens and to change their min token length in mysql to 2 instead of 3.

But still you need to build it so that each matched short token/like token gets a bonus score based on the short token weight. You also should make it so the short token length is configurable - e.g. if someone DOES change their min token length down to 2 in mysql, our code needs to now only count 1 character tokens as short tokens and make sure tokens with 2 characters or more go to the fulltext engine and not the LIKE operators array.

**Comment by dhilditch** [comment]
@hmkayani I'm reassigning this back to you but PLEASE, IT'S IMPORTANT:

PLEASE FIGURE OUT a way so you can get ALERTS and you know that I replied. This bug is one I told you was priority and I replied within 10 minutes of your question and you never came back to this bug.

If you need help getting github actions set up so that you get messaged on Discord or something, please can you ask @Glynnage for help.

I know you can do this but we need better communication - this bug was top priority 3 weeks ago but I've been swamped and could not do it - I assigned it to myself after you left it sitting for a week after you'd asked your question.

Simpler would be just to enable github email alerts and configure some audible alert with gmail + labels or something, but if you want messages sent to discord, we can help you with that.

**Comment by hmkayani** [comment]
@dhilditch I have added the shorttoken weight to the weights list
Currently short token length is hard coded in code as "3" so I needed to ask if I have to add some frontend field to let users enter short token length or just change the length in code from "3" to "2"

**Comment by dhilditch** [comment]
Add a definition for the short token length - defaulted to 3.

Users MUST be aware when they change this that they must also change their mysql config to change the minimum token length there.

But this refactoring is not the number 1 priority here. The number 1 priority here is to get each short token to have its score boosted when it matches with a like.

**Comment by hmkayani** [comment]
@dhilditch can you please check if the score boosting is working fine 
https://github.com/superspeedyplugins/super-speedy-search/tree/179-short-token-multiplier-not-working-for-super-speedy-search

**Comment by dhilditch** [comment]
Can you please share screenshots of a search results page with the short token multiplier set to 100 and weights visible and then a second screenshot with short token multiplier set to 1000?

That will tell us if it's working.

**Comment by hmkayani** [comment]
![Screenshot](https://github.com/user-attachments/assets/eb63d1e8-ad6c-496e-99e3-60280681576f)
![Screenshot (1)](https://github.com/user-attachments/assets/319107df-9bba-49a3-83ad-590439770fef)

**Comment by dhilditch** [comment]
![image](https://github.com/user-attachments/assets/bf8b2284-0346-4fa5-848e-61f16a398ce7)

Ok - this definitely looks wrong - I don't know what you searched with here, but the 2 items on the right do not have ANY short tokens, so they should not be getting any short token boost.

**Comment by hmkayani** [comment]
@dhilditch basically what I searched is "wi fi 6" and Strict Search is set to "Match any words" and Whole Word Search set to "Wildcard suffix"

**Comment by dhilditch** [comment]
Ok - so there are two parts here - it's correct that "wi fi 6" will match the word "with" but it's not correct that the word 'with' gets a short token boost.

To calculate short token boosts, you need to tokenize the title of the item. e.g. a title "wi-fi 6" would get tokenized to [wi, fi, 6] in an array and then any matching items should get the score boost. e.g. a product call "Collar with studs" would not match, the tokens would be [collar, with, studs] and none of these match the short tokens from the search string.

For tokenization, you basically use any word separator - spaces, commas, periods, dashes, exclamation marks etc.

Maybe this is quite complicated to produce this score using SQL but it should be possible.

Here's Claudes (the AI) approach based on an educated prompt from me:

```
-- Create a table to store your data
CREATE TABLE items (
    id SERIAL PRIMARY KEY,
    name TEXT
);

-- Insert some sample data
INSERT INTO items (name) VALUES
    ('Wi-Fi 6'),
    ('Collar with studs'),
    ('Wireless Fi'),
    ('WiFi Router');

-- Query to search and boost scores
WITH short_tokens AS (
    SELECT unnest(ARRAY['wi', 'fi']) AS short_token
),
item_tokens AS (
    SELECT 
        id, 
        name, 
        regexp_split_to_table(
            lower(regexp_replace(name, '[^a-zA-Z0-9]+', ' ', 'g')),
            '\s+'
        ) AS token
    FROM items
),
matches AS (
    SELECT 
        i.id,
        i.name,
        COUNT(DISTINCT s.short_token) AS match_count
    FROM 
        item_tokens i
    JOIN 
        short_tokens s ON i.token = s.short_token
    GROUP BY 
        i.id, i.name
)
SELECT 
    id,
    name,
    match_count AS boost_score
FROM 
    matches
WHERE 
    match_count > 0
ORDER BY 
    match_count DESC, name;
```

Hopefully that makes sense - obviously if there are no short tokens we don't need this extra CTE, but possibly it wouldn't hurt performance if you just set that SQL array to an empty set.

**Comment by dhilditch** [comment]
An extra consideration here - we definitely cannot run this regex against the whole database, so it should be running against the already filtered results.

i.e.

Current code filters using full text search + LIKE operators. Like operators do broad match, e.g. 'wi' short token will match 'with'

This query should then be a subquery for the short token scoring mechanism above. This will ensure the regex is only running against already matched items rather than scanning the entire table. It's an absolute must that this remains fast with > 1 million items in wp_posts.

**Comment by dhilditch** [comment]
Also - please put this regex into defines.php (don't put it in the interface).

[^a-zA-Z0-9]+

Some websites will not want e.g. / or ! to be treated as separators, it depends on their content. So if I get a support question from one of them in future for this, I will be able to give them something to put into their wp-config.php and then once we see the kind of configs people have for that we can maybe move that config into the interface.

**Comment by hmkayani** [comment]
@dhilditch , I've updated the code and attached the revised images

![Screenshot (2)](https://github.com/user-attachments/assets/5271e0c5-f525-4359-96ef-b87e5250db4f)
![Screenshot (3)](https://github.com/user-attachments/assets/89efda1c-eea8-4e87-b208-c706c5e8d6e5)
![Screenshot (4)](https://github.com/user-attachments/assets/b678a0b3-de68-45b5-a21a-e725d2e5ccf6)
