### ISSUE TITLE
Disable load more button

### ISSUE THREAD

**Issue by Starfiniti** [superspeedyplugins/issue-tracker#18]
As per the discord conversation, I'm requesting a feature where I can disable the load more button or at least be able to configure it to show much later.

**Comment by dhilditch** [comment]
We added some extra options in version 1.47 (20th December 2023) to control when the load more button loads.

Added some new pagination options
* choose how many pages to scroll before load more button appears
* second load more button option after a different number of pages, e.g. default load 3 pages, show load more, then load 10 pages, then show load more ad infinitum
* scroll to infinity checkbox option will prevent the load more buttons appearing more than once
