### ISSUE TITLE
Add our branding to our invoices

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#184]
1. Visit Dukies order page https://www.superspeedyplugins.com/wp-admin/post.php?post=1689479&action=edit
2. Switch users to Dukie
3. Notice that the logo is tiny somehow and it just says INVOICE at the top left

![image](https://github.com/user-attachments/assets/5b4b29b6-09ff-4964-a268-bb405fba4f87)

Fix it so the branding is better and our logo is better.

**Comment by Glynnage** [comment]
Removed barcode, reduced font size on "INVOICE" and enlarged logo
