### ISSUE TITLE
Scalability Pro pagination removal is affecting Woo subscriptions but no next page has been added

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#188]
You previously added a Next Page button for woo orders.

Please look at that code and alter it so that a next page button gets added to all wp-admin archives if this option is enabled.

I'm fairly certain no prev-button is required since I think once you go to page 2+ that spro switches off its functionality, i.e. the pagination returns on page2+.

1. Install woo subscriptions
2. Enable spro option to remove pagination from wp-admin /SQL CALC NO FOUND ROWS option
3. Add a bunch of subscriptions so you paginate
4. Test page 1 - confirm next page button added
5. Test page 2 - confirm pagination returns

Would be useful if you could test pagination on other wp-admin pages, but if the code is generic enough with JS, it should work with all wp-admin archives.

**Comment by hmkayani** [comment]
@dhilditch , I have added the "Next Page" button on the subscriptions page, but the pagination is not being removed.
I think the query is not in the main loop so "pre_get_post" is not triggered.
is there anything i am missing here.

**Comment by dhilditch** [comment]
Did you enable the spro options which remove pagination?

**Comment by hmkayani** [comment]
Yes, the option to remove pagination is enabled. It is working on pages like admin products lists page

**Comment by dhilditch** [comment]
Fixed in latest
