### ISSUE TITLE
SSF - Hide filters if the displayed products dont use those filters?

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#19]
**Describe the bug**
For clarification - When using WOOF / Husky product filters the product archive pages only show the filters relevant for the products in the category.

For example - A laptop will have RAM and CPU and we dont want those to display for Laptop Bags for example.

**Does SSF also have this behaviour only showing relevant filters?**

Our store has 600 variations split over 60,000 products in different categories. So hiding irrelevant categories is a key function we need otherwise we will see all of those variations.

Note the customer is hopefully going to select the top 100 filters vs adding all of them one by one as widgets.

**To Reproduce**
1. Add SSF to widget area with attributes associated with category 1 - Product 1 contains those attributes
2. When viewing a different category or attribute where product 2 has different attributes our widget should be hidden because the products shown dont have those attributes set.

**Expected behavior**
Attribute filters should only be visible if they apply to the category or attribute archive shown.
I.e. Laptops category containing products with CPU attribute - Should show CPU filters
Whereas laptop bags in their own category containing bags should not show CPU because the attribute doesnt apply to these products.

Hard to put in writing. Hopefully the above makes sense. Its a deal breaker for us if we cannot hide unused filters!

**Comment by dhilditch** [comment]
This is also how SSF normally behaves unless you choose the option to 'ignore other filters'.

**Comment by dhilditch** [comment]
I cannot reproduce this unless I set a widget to 'Ignore other filters' rather than 'Respect other filters'.

Please can you check that and find me on Discord if you still struggle.

**Comment by thinkjarvisdesignandmarketing** [comment]
I'll double check the settings and the filters. I can also check this on a couple of other sites if necessary.
