### ISSUE TITLE
Relative URLS incorrect in Super Speedy Search

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#2]
**Describe the bug**
When running https://www.domain.co.uk/wpinstallfolder/

This is a staging url for a site

The AJAX dropdowns are not correctly using the site urls.
the /pinntecstaging/ is missing from the url

**To Reproduce**

1. Set up a site in a folder that is not the root folder
2. Install Super Speedy Search
3. Activate it and activate ultra ajax
4. watch in horror as the console shows the wrong url
5. therefore ajax dropdown does not populate

**Expected behavior**
The right URL to be used in console
Ajax to display results

**Screenshots**
See
below:
The relative url is missing for the script.

**Desktop (please complete the following information):**
Desktop, Win10, Chrome
Latest versions of WP and all plugins

![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/b7a695b3-982b-4c42-b1a6-ad6bcb83c27c)

**Comment by dhilditch** [comment]
Fixed in 4.33
