### ISSUE TITLE
SSF: Add support for shop base / shop category base permalink changes

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#20]
**Is your feature request related to a problem? Please describe.**
One of my clients is using https://masterns-studio.com/code-factory/wordpress-plugin/woo-category-base/
This plugin adds some re-directs that allow the shop base and the product category base to both be equal or both be /shop/ in our example.

**In Settings > permalinks**
Product category base is set to shop
and
Product Permalinks is set to:
/shop/%product_cat%/

This plugin for each product category adds a re-write rule that prevents 404 errors - By default WordPress wont allow the shop base to be used for products and categories.

/shop/product-category/product for all
instead of
/shop/product
/product-category/product

The plugin scans the shop categories and adds a rewrite rule to each.

**Describe the solution you'd like**
Is it possible to add a setting under SSF > Advanced to allow for this structure?

**Describe alternatives you've considered**
Removing the custom plugin - This is a £1m+ turnover store that I host and optimise. The SEO consequences of removing this plugin would be huge so I am reluctant to tell the client that they need to uninstall the plugin for compatibility with SSF.

An option to allow for this situation would really help.

**If there is already an option that would make this work please let me know**

**I can probably give you access to the client's dev site to test possible solutions.**
**A copy of the plugin can be provided for testing purposes**

**Comment by dhilditch** [comment]
Please ask me more about this on Discord if the below does not make enough sense.

You can already achieve what you need:

1. Change Product Category permalink to normal 'product-category'
2. Uninstall that other plugin
3. Change Settings > SSF > URL Structure > Product Category -> Then check the box to remove /product-category/ from the URL

Then you can have /shop/{product_url}/ and /shop/{product_category}

**Comment by dhilditch** [comment]
Just to confirm from before - my last advice was not great, it would have meant you'd have /shop/product-x/ and /adidas/ rather than /shop/adidas/

Anyway, on my local, without the plugin you mentioned, I visited Settings > Permalinks and set 'shop' as the Product category base.

https://i.imgur.com/SfNoB4l.png

Then I went to the /shop/ page and all our categories are now /shop/adidas/ etc and they do load the products properly.

https://i.imgur.com/zgcqVVT.png

**Comment by thinkjarvisdesignandmarketing** [comment]
I'll get back to you once I've tested this option. I'll have an up to date test area tomorrow morning.

By default when the permalink options for product archives include shop it breaks the structure if the suop base is also shop. Looking at your suggestion if we are talking an Easy to implement redirect then the seo damage will be minimal.

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 

This kind of works but means product categories when viewed are not part of the shop structure.

you cannot set the shop base to be the same as the category base. They cannot both be /shop/

It is possible to add /shop/product-category/ as the shop category base and the product base but this will add product-category to the string when viewing a product.

A nice workaround though. I'll see if the client approves as it means we can use SSF properly.

**Comment by thinkjarvisdesignandmarketing** [comment]
Hi @dhilditch,

I've just ran a test on this.
This is an active bug still can you reopen this?

If you set the following config - It breaks multiple selections on filters. The URLs do not display properly and you cannot set more than one filter:

So if I am in a category and select a size filter it then only filters by size and loses the category.

Its supposed to filter by category and an attribute not one or the other.

Removing shop/from the product category base and it works properly again.

Please can you take a look at this?

I agree we dont need support for the plugin I suggested you can do this out of the box with WooCommerce but its causing a bug with the filters when you do it this way.

See screenshots these are the settings:
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/f1258355-24f4-44a3-9153-0205560d54a9)
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/4e0aa591-8c94-4265-bbaf-56aa518454d1)

This is the problem with the permalinks. Set a category and then filter by an attribute and it only does one or the other.
This is supposed to be domed name badges and rectangular shape but it breaks the pretty permalinks and multi select when the settings above are enabled.
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/75b398f5-fc98-4d3f-976e-c28a17525080)

When shop is removed from category base it correctly applies both filters:
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/1589f6bc-7319-477c-982f-984055173808)

**Comment by thinkjarvisdesignandmarketing** [comment]
Thanks Dave,

I have a client who specifically wants this permalink structure. We have delayed rolling out SSF to the site so appreciate you looking into this.

Theres no rush this end at the moment but this would also be my preferred URL structure on other new projects. So would be useful to get this working. Thank you.

**Comment by dhilditch** [comment]
@voodoo911 can you update me on the status of this one please?

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
You can also set the attribute slug here: Setting this also breaks all attribute filters.
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/9b7eaf3e-5715-4144-9a08-9f95939415f7)

Sorry to add to the issue. The filters break if you put anything in this box not just changing it to a shop base URL.

**Comment by dhilditch** [comment]
@hmkayani Can you download and install SSF and familiarise yourself with this plugin please? It is definitely our most complicated plugin.

The first issue I would like you to fix is the one from the last screenshot above.

1. Load some sample products for woocommerce or use an existing local dev shop you have
2. Install SSF and run the table build - there will be a notice in wp-admin about this or you can check settings > ssf > Advanced tab
3. Install the classic widgets plugin to make using the widgets a lot easier
4. Add a category widget and an attribute widget - i.e add 2 Super Speedy Filters widgets, choose 'product', hit save, you'll see all the options appear, choose 'product category' for one and whatever attribute for the other
5. Check they work on the front end
6. Visit Settings > Permalinks and add an extra base for product attribute base 
7. Confirm attribute filters are now broken

Track through the code and fix this issue. Let me know any questions on discord.
