### ISSUE TITLE
Super Speedy Filters - Replacement for default sort order filters

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#207]
https://github.com/superspeedyplugins/issue-tracker/issues/206

Replacement query for default sort order queries.

When super speedy filters is enabled the default sort filters stop working. This means there is no way to filter by price as a one click action when Super Speedy Filters is on.

Please check the issue raised first in case there is a viable solution already available.

**Comment by dhilditch** [comment]
closing duplicate
