### ISSUE TITLE
urgent: Pagination disappears from Search results. Compatibility issue with SSS and Auto Infinite Scroll.

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#235]
**PLEASE COMPLETE ALL STEPS TO SPEED UP BUG FIXES**
Since upgrading to the latest plugins - The pagination is being removed compeltely from our search results page.

Therefore Auto Infinite Scroll is not working on the search results.

This problem was not occuring in the previous release of the plugins.

**If I disable Super Speedy Search the pagination is displayed and Auto infinite scroll works on the search page - So it appears to be a problem with Super Speedy Search's output in the latest version.**

**This problem only occurs on the search results page.**

Please can you advise. It is affecting our live sites.

**IMPORTANT CONTEXT**
Using latest version of all plugins and wordpress
Enfold theme 6.06

Tell us what you have tried so far.
Rebuilding the index for SSF and SSS
This does appear to be a general problem NOT enfold specific - The problem was not occuring before we updated the plugins. The theme version has not changed.
Disabling Super Speedy Search restores the pagination output to the search results page - therefore auto infinite scroll starts working again

Please message me on discord and I can give you access to one of the sites if required.

**Comment by dhilditch** [comment]
Fixed in last weeks release
