### ISSUE TITLE
Super Speedy Search Ajax suggestions (Products) is ignoring visiblity hidden from catalogue and search settings

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#236]
PLEASE COMPLETE ALL STEPS TO SPEED UP BUG FIXES
The client has products in their store set to hide from catalogue and search.

This setting is being ignored by SSS > Ajax Search > Search Ajax Post Types > Products.

We need a feature or an option to filter out items that are supposed to be hidden from the shop.

The client has reported that the search results look OK - It is just the ajax dropdown that is ignoring the hidden from search and catalogue rules.

**Tell us which version number of our plugin(s) you are using.**
5.08

Tell us what you have tried so far.
The client has disabled the product suggestions for now but they are a £1m+ turnover store so we need to get this working again asap.

Given the size of the site I will need to get permission from their developer to give you access to this - I may have to give you a different site with some dummy products on it if you need to investigate on one of our sites.

**Comment by dhilditch** [comment]
Fixed in last weeks release
