### ISSUE TITLE
Divi Compatibility problem with Super Speedy Filters

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#241]
**PLEASE COMPLETE ALL STEPS TO SPEED UP BUG FIXES**
When using the custom Theme builder in Divi by Elegant Themes - If you use a Super Speedy Filter and set display container type to any of the open or close options it wont open or close on the front end of the site.

We have tried disabling plugins and removing custom JS.

We are running the latest version of Super Speedy Search, SPRO, Filters, Auto Info Scroll.

If you require test area access please let me know. This is on a test site right now.

**Comment by dhilditch** [comment]
@thinkjarvisdesignandmarketing is the theme builder removing our plugins .js files?

Or maybe it bypasses the regular widget container code and uses a different container?

**Comment by thinkjarvisdesignandmarketing** [comment]
Im not sure. Not seeing any console errors.
The test area is below with a SSF category element that wont show or hide

You can see it here: https://www.tjdm.co.uk/thinkdivishop/shop/

**Comment by thinkjarvisdesignandmarketing** [comment]
I've fixed it - If I set the builder to use one of the SSF widget areas it works.
