### ISSUE TITLE
Filter terms which load via AJAX are not working for SSF

### ISSUE THREAD

**Issue by theo-gk** [superspeedyplugins/issue-tracker#246]
I use the latest SSF plugin v6.0.1. My attributes filter have many many terms, so I use the ["Items per page (Ajax)" setting](https://prnt.sc/g08kBVjoPkGl) in my widgets set to "20" in order to load the rest of the terms via AJAX. 

The first 20 terms are working fine. When I scroll to the bottom the next 20 terms appear but they don't work when I click them. The same problem happens for terms loaded via AJAX using the widget's search input.

There is a difference in the href attribute between the 2 cases, as the AJAX-loaded terms have `href="javascript:void(0);"` instead of the filter link:
[An href attr for the first 20 terms](https://prnt.sc/r3ML6aHE496B)
[An href attr for a term loaded later via AJAX](https://prnt.sc/o0sfoi4YFXpD)

Other (maybe unrelated) info:
I use the "Use full page loading everywhere" option
I use these overrides in wp-config file:
define('SSF_MAKE_FILTERS_BE_FILTERED_BY_SEARCH', true);
define('SSF_REMOVE_SHOP_FROM_BREADCRUMBS', true);
define('SSF_SHOW_PARENTS_PER_TERM_IN_BREADCRUMBS', true);
I use Redis but I have flushed it multiple times.
I use WPRocket but I have flushed it multiple times.

Thanks Dave, I will appreciate a solution because most filters are unusable right now except for the first 20 terms.

**Comment by theo-gk** [comment]
I have an update. The issue seems to be related to these [2 options](https://prnt.sc/7TOdpjNnRw44):
- Maximum indexable taxonomies
- Maximum indexable terms

When I select an option with nofollow in either of them, then the terms loaded via AJAX are not working.
If I select follow for both of them, then all terms work fine.

But I do want them to be "nofollow". My site is pretty huge and I don't want the bots to follow all my filter links and stress my server for no reason.

Can you provide a solution?
Thanks

**Comment by dhilditch** [comment]
Fixed in 6.02
