### ISSUE TITLE
Undefined variable - Super Speedy Filters - class-ssf-tax-widget.php line 38

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#250]
I am seeing the following error cropping up repeatedly in my Plesk logs.

Any idea why we would be getting this?

AH01071: Got error 'PHP message: PHP Warning: Undefined variable $handling_ajax in [REDACTED LINE HERE FOR BUG REPORT/httpdocs/wp-content/plugins/super-speedy-filters/class-ssf-tax-widget.php]

**Comment by dhilditch** [comment]
Fixed in 6.06

**Comment by thinkjarvisdesignandmarketing** [comment]
legend cheers @dhilditch !
