### ISSUE TITLE
Compatibility issue SSS and Bulk Variations Plugin - huge memory spikes and server crashes

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#252]
We are seeing huge Mysql memory use on our server when our cache warmer runs on a particular website of ours.

![image](https://github.com/user-attachments/assets/4033efda-8193-4358-9f3d-e90234ae4f0b)

You can clearly see the correlation between the cache warmer and the mysql memory usage. For context. We have another site running pinntecdirect.com and the memory spikes do not occur during the warm of their 60,000 products.

**THe following error occurs multiple times on each product page visited by real visitors, bots and our cache warmer.**

`AH01071: Got error 'PHP message: PHP Warning: Undefined array key "product_variation" in [/var/www/vhosts/abalonegraphics.com/httpdocs/wp-content/plugins/super-speedy-search/includes/sss.php] on line 1534; PHP message: PHP Warning: Trying to access array offset on value of type null in [/var/www/vhosts/abalonegraphics.com/httpdocs/wp-content/plugins/super-speedy-search/includes/sss.php] on line 1534;`

This error is occuring multiple times on each page.

I can see in plugins/woocommerce-bulk-variations/templates/single-product/variable-grid.php on line 73 and 105 that it references the post type.

![image](https://github.com/user-attachments/assets/b2f89527-7e69-4120-b6ba-79cce1dd1c4d)

![image](https://github.com/user-attachments/assets/e016dec3-64be-43f0-97fa-5ac54905877c)

This site is the only site we have that uses this plugin.

Plugin is here:
https://woocommerce.com/products/bulk-variation-forms/

This website relies heavily on cache due to the number of queries required to build the bulk grids.

**The cache warmer and wp-rocket cache folder do not appear to be populating properly.**

Please can you advise?

Our server is really struggling.

I am having to restart mysql, mysqld and mariadb every few days as the memory fills and does not clear.

**Comment by dhilditch** [comment]
Switched off sss when called from inside the cart list, in 5.19
