### ISSUE TITLE
When Scalability Pro Remove Image Size option is enabled with Kadence theme, Kadence blocks goes nuts

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#29]
Kadence blocks theme ends up doing something with image sizes and a 1s page now takes 3s with 2x more SQL queries.

1. Install kadence & blocks on a Woo site.
2. Visit a product detail page with Query Monitor active, note the query count and page time
3. Activate Scalability Pro, visit the Settings > Scalability Pro > Imports tab, click to enable image removal globally, then check all the boxes to keep all image sizes
4. Visit the product detail page again and note the increased query count and increased page time

The function seems to be related to the function Kadence_Image_Processing->create_image_size() and the Remove Image sizes option in Scalability Pro.

![image](https://github.com/superspeedyplugins/issue-tracker/assets/3008613/51b46899-891d-4dc2-8f4e-22702f79bf25)

I remove image sizes using an on-the-fly tecnique, so maybe that should be improved.

The quickest solution would be to trace this code and probably investigate the kt_woo_get_image_array() function and possibly we just add something to Scalability Pro image sizes so that our code doesn't run before kt gets the image array or something?:

`update_metadata()
wp-includes/meta.php:250
update_post_meta()
wp-includes/post.php:2558
wp_update_attachment_metadata()
wp-includes/post.php:6513
Kadence_Image_Processing->create_image_size()
wp-content/plugins/kadence-woo-extras/classes/class-kadence-image-processing.php:178
Kadence_Image_Processing->process()
wp-content/plugins/kadence-woo-extras/classes/class-kadence-image-processing.php:106
KT_WOO_Get_Image->process()
wp-content/plugins/kadence-woo-extras/classes/class-kadence-woo-get-image.php:81
kt_woo_get_image_array()
wp-content/plugins/kadence-woo-extras/classes/custom_functions.php:247
Kadence_Shop_Kit_Product_Gallery->output_gallery()
wp-content/plugins/kadence-woo-extras/lib/gallery/class-product-gallery.php:841
Kadence_Shop_Kit_Product_Gallery->render_gallery()
wp-content/plugins/kadence-woo-extras/lib/gallery/class-product-gallery.php:447
kadence_wootemplate_render_gallery_block()
wp-content/plugins/kadence-woo-extras/lib/templates/blocks/gallery-block.php:83
WP_Block->render()
wp-includes/class-wp-block.php:258
WP_Block->render()
wp-includes/class-wp-block.php:244
WP_Block->render()
wp-includes/class-wp-block.php:244
WP_Block->render()
wp-includes/class-wp-block.php:244
WP_Block->render()
wp-includes/class-wp-block.php:244
render_block()
wp-includes/blocks.php:1484
do_blocks()
wp-includes/blocks.php:1522
apply_filters('kwootemplate_the_content')
wp-includes/plugin.php:205
Kadence_Woo_Block_Editor_Templates->output_woo_template()
wp-content/plugins/kadence-woo-extras/lib/templates/woo-block-editor-templates.php:1053
Kadence_Woo_Block_Editor_Templates->get_product_content()
wp-content/plugins/kadence-woo-extras/lib/templates/woo-block-editor-templates.php:967
do_action('kadence_woocommerce_template_product_override')
wp-includes/plugin.php:517
`

**Comment by dhilditch** [comment]
Testing the labelling github action

**Comment by dhilditch** [comment]
Test 2

**Comment by dhilditch** [comment]
The proper solution for this should just be to remove the image sizes from the database, i.e. unregister them. This will be more performant and compatible.

**Comment by dhilditch** [comment]
Something like this code can be used to handle this:

```
<?php
class ScalabilityProImageSizeManager {
    public function __construct() {
        add_action( 'init', array( $this, 'deregister_image_sizes' ) );
    }

    public function deregister_image_sizes() {
        // Assuming $image_sizes_to_keep is an array of image size names you want to keep.
        // You could retrieve this array from your plugin's configuration, for example:
        // $image_sizes_to_keep = get_option('scalability_pro_image_sizes_to_keep', array('thumbnail', 'medium', 'large'));
        $image_sizes_to_keep = ['thumbnail', 'medium', 'large']; // Example sizes to keep

        // Get all registered image sizes
        global $_wp_additional_image_sizes;
        $registered_sizes = get_intermediate_image_sizes();

        foreach ($registered_sizes as $size) {
            if (in_array($size, $image_sizes_to_keep)) {
                continue; // Skip sizes that we want to keep
            }

            // Sizes registered via add_image_size() are stored in $_wp_additional_image_sizes
            if (isset($_wp_additional_image_sizes[$size])) {
                remove_image_size($size); // Deregister size
            }
        }
    }
}

// Initialize the class in your plugin file
new ScalabilityProImageSizeManager();
```

**Comment by dhilditch** [comment]
The existing image size code needs to be removed, the code above should be added and then hooked into whatever the admin has selected - i.e. if they selected to keep full size and thumbnail then remove everything else.

**Comment by voodoo911** [comment]
Version 5.45lass ScalabilityProImageSizeManager  and

**Comment by voodoo911** [comment]
Version 5.45
Implemented class ScalabilityProImageSizeManager  and removed all old functionality related to image sizes remove
