### ISSUE TITLE
External Images Plugin bug?

### ISSUE THREAD

**Issue by RexHavoc69** [superspeedyplugins/issue-tracker#3]
**Describe the bug**
External Images Plugin

When uploading new images to products with WP All Import, the original image still shows in the results and single product page.
The new image URL is in the external_image_url and is the only image.
The correct image displays in the External Featured Image box on the edit page.
If you share a link to the product the correct image shows in the thumbnail.
You can not manually edit the external image field.
The only fix I have found is to delete the product and re-upload it.

**To Reproduce**
Upload and overwrite the current image for the product.

**Expected behavior**
The new image should display as it is the only one entered into the external_image_url field.

**Screenshots**
![image](https://github.com/superspeedyplugins/issue-tracker/assets/92769963/cd86854f-be97-4f57-8a44-2dd0db3c29e4)
![image](https://github.com/superspeedyplugins/issue-tracker/assets/92769963/32766625-c395-4c7f-8fb0-daba3ed6bcc8)
![image](https://github.com/superspeedyplugins/issue-tracker/assets/92769963/ed9afdec-69b3-4ddb-90ba-e40b1b74e839)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox, Edge, Opera, Chrome
 - Version n/a

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dhilditch** [comment]
I need a little clarification:

> Upload and overwrite the current image for the product.

How are you overwriting the current image? I ask because you then say:

> You can not manually edit the external image field.


If you *do* overwrite the external_image_url field, then we have a do_action hook which deletes ei_converted postmeta.

If you are updating the external_image_url field in order to change the image, you either must have do_action calls enabled or you must delete the ei_converted postmeta field at the same time.

**Comment by RexHavoc69** [comment]
Hi Dave

 

Im using WP All Import to overwrite the contents of the external_image_url field if/when new images become available.

do_action calls are enabled. 

 



 

How do I delete the ei_converted postmeta field during this process?

 

 

 

Best Regards

Mark Francis
Managing Director
 <https://pp.co.nz/> Paradigm PCs Ltd

**Comment by dhilditch** [comment]
Rather than delete, you could just set ei_converted to empty. If you have do_action calls, can you also confirm if you have the option enabled in the settings to create the mappings automatically upon import?

**Comment by RexHavoc69** [comment]
Hi Dave.
Please excuse my ignorance here. Where do I find this setting 'ei_converted'? Based on your earlier comments I probably need not worry anyway?
The mappings in WP All Import were created manually.

**Comment by dhilditch** [comment]
This sounds like a caching issue I think.

If this happens again, can you double check by adding ?v=1 to your product URL to bust the page cache and fetch a fresh page.

Note: re editing external_image_url field, on the edit product page to to Screen Options > Custom Meta and enable that check box, now you will be able to edit the external_image_field, but given that you said it is working literally everywhere except one or two front-end places, it's almost certainly a caching issue.

**Comment by RexHavoc69** [comment]
I thought this too at first but caching was not enabled at the time. The issue seems to be resolved however so you can maybe close this bug report.
