### ISSUE TITLE
Featured Image not displaying in Admin Columns plugin on all posts page

### ISSUE THREAD

**Issue by Glynnage** [superspeedyplugins/issue-tracker#33]
**Describe the bug**
After making a custom "Featured Image" column for posts, using the "Admin Columns" plugin, External Images doesn't display the featured image in the column. Regular featured images work fine.

**To Reproduce**
1. Install External Images and activate
2. Download and install Admin Columns: https://wordpress.org/plugins/codepress-admin-columns/
3. Settings > Admin Columns > Select post type (Posts) > Add Column > Type & Label = Featured Image.
4. Create New Post > Add External Featured image > Check Posts page

**Expected behavior**
Image displaying in "Featured Image" column

**Screenshots**
https://i.imgur.com/UCgeVbw.png

**Comment by hmkayani** [comment]
I am trying to replicate this issue can you tell me how are you adding external feature image?
I have tried using the plugin "Featured Image from URL (FIFU) https://wordpress.org/plugins/featured-image-from-url/" but could not replicate the issue.

**Comment by dhilditch** [comment]
New plugin for you @hmkayani - this involves downloading our external images plugin, downloading the admin columns plugin, creating a couple of posts or products with external featured images then in admin columns you can add the featured image to a particular view and you'll see that the featured image from their plugin is still pulling the uploaded featured image.

This will take you a little bit to understand how this plugin works and how we overrule WP behaviour and avoid the need to upload images, but figure that out and figure out where Admin columns is pulling the featured image from and from then you should be able to fix the thumbnail featured image in wp-admin when admin columns is in use.

**Comment by hmkayani** [comment]
This issue is fixed in version 3.12

**Comment by dhilditch** [comment]
Merged in version 3.13
