### ISSUE TITLE
Add 'search whole words' option next to Exact search option in SSS

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#37]
In SSS, there is an option to search exact words or any words.

Currently this makes the fulltext search behave like this for '4070 super'

* Exact: +4070* +super*
* Any: 4070* super*

This new setting should have two options:
* Wildcard suffix - add a wildcard to the end of each searched word
* Search whole words - match entire words

Default this to Wildcard suffix and ensure that users who upgrade do not get a warning if this setting does not yet exist.

Then, in the search code that you altered in the last job find the getSQLStatements part and read this new setting and then if Search Whole Words is chosen, do not add the * wildcard to the end of the words being searched.

**Comment by dhilditch** [comment]
To test this, you can create two posts with titles:

4070 super
4070 superior

Then with whole word search only the first one should be returned when searching 4070 super.

**Comment by hmkayani** [comment]
This issue is fixed in branch "Search issue fix" and version "4.39"

**Comment by dhilditch** [comment]
Fixed in 4.39 - new 'search whole words' option added, provides 4 options when combined with exact search.

Search whole words effectively removes the wildcard suffix from the searches so '4070 super' will not match with '4070 superior' if whole word search enabled.

**Comment by RexHavoc69** [comment]
I have updated to v4.41 and selected 'Search Whole Words'. I have then rebuilt the table.
Searching "4070 Super" (within quotation marks) should only return results that have this exact phrase.
This does not appear to be working? Im getting results that have both words, but not the exact phase.
Any ideas?

**Comment by RexHavoc69** [comment]
Also noticed an error in Query Monitor when using the quotation marks for the exact phrase search '"4070 Super"'.
No error if I enter '4070 Super' without quotation marks...

Invalid argument supplied for foreach()

    wp-content/plugins/super-speedy-search/includes/sss.php:316
    SSS::getSearchSQL()
    wp-content/plugins/super-speedy-search/includes/sss.php:866
    SSS->sss_pre_get_posts()
    wp-includes/class-wp-hook.php:324
    do_action_ref_array('pre_get_posts')
    wp-includes/class-wp-query.php:1881
    WP_Query->get_posts()
    wp-includes/class-wp-query.php:3824
    WP_Query->query()
    wp-includes/class-wp.php:696
    WP->query_posts()
    wp-includes/class-wp.php:816
    WP->main()
    wp-includes/functions.php:1336
    wp()
    wp-blog-header.php:16
