### ISSUE TITLE
Adding media through New Post > Featured Image not updating SSS table

### ISSUE THREAD

**Issue by Glynnage** [superspeedyplugins/issue-tracker#39]
**Describe the bug**
When adding a brand new image to the Media Library through the Featured Image area, Super Speedy Search Table does not update - so if we use SSS on the back-end, the added image will not display in search results. After rebuilding table, the image displays in search results

**To Reproduce**
1. Activate Super Speedy Search
2. Go to Settings > Super Speedy Search > Main: Enable “Override Back-end Search Results”
3. Download new image - name something unique
4. Create new post > Set Featured Image > Upload Image
5. Go to Media > Library > Search for image

**Expected behavior**
At this point, we should see the image in the "file" column.

**Screenshots**
Search: https://i.imgur.com/HGh4YzR.png
Result: https://i.imgur.com/UVsqRtS.png

Go to Settings > Super Speedy Search > Advanced > Rebuild tables
Search image again
Search: https://i.imgur.com/dVfmx7l.png
Result: https://i.imgur.com/irZCIVW.png

**Comment by dhilditch** [comment]
Correction - add and edit media is fixed, delete images still not fixed

**Comment by dhilditch** [comment]
Fixed in 4.38
