### ISSUE TITLE
Add shop order filter option to stop woo scanning orders to promote their payment plugin in Scalability Pro

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#41]
```
add_filter( 'woocommerce_allow_marketplace_suggestions', function( $allow ) {
    return false;
});
```

Add option to settings of scalability pro to allow users to disable that stupid query by Woo.

**Comment by dhilditch** [comment]
This setting should be added to the wp-admin tab.

Option name: Disable WooCommerce Marketplace Suggestion
Description: For high-order websites, you will find all your wp-admin pages are slowed down since a table scan of orders is happening every time you load a wp-admin page if a new order has arrived since the last time you loaded a wp-admin page. This slowness comes from WooCommerce running a select count(*) of your orders from the past 90 days which tends to run a table scan, and the purpose is only so they can decide to try and market their services.

**Comment by voodoo911** [comment]
Added in version 5.46
