### ISSUE TITLE
SSF overriding shop titles and breadcrumbs even with those options switched off (thinkjarvis)

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#42]
1. Disable shop title and breadcrumbs
2. Navigate to a child category
3. Breadcrumbs are showing only shop
4. Title is showing as if just on shop

Need to integrate this with Yoast.

Ideally just need to keep the taxonomy queried_term for Yoast to work.

Enable debug with Yoast and check with SSF running what happens.

/product-category/computing-and-peripherals/mobile-phones-and-smartwatches/mobile-accessories/
(above is single term, hierarchical category)

https://discord.com/channels/837258064704438282/877862826528620554/1197582719543152640

**Comment by dhilditch** [comment]
This is related to the permalink catch-all rewrite we have - our category permalink should be prioritised AFTER the other permalink rewrite URLs so that the regular WooCommerce permalink takes priority here.

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch Keep me posted on this - It is a big SEO problem for my client. Do we have an ETA as to when this issue will be looked at?

If you want a test area for the client site let me know and I'll do a staging site for you (Or if you think your changes wont cause too much issue - Access to the live site)

**Comment by thinkjarvisdesignandmarketing** [comment]
Hi David,

Any ETA on this - I am working on a site that is using the full Super Speedy Stack from scratch with a March 1st launch date right now.

This is a big SEO problem.

**Comment by dhilditch** [comment]
Looking at this today and tomorrow, should have a fix out by this weekend.

**Comment by dhilditch** [comment]
This should be fixed in 5.21 which should be released tomorrow. Note: You will need to disable the two options in Advanced tab (everything else should still work with those disabled with 5.21)

https://i.imgur.com/zPVRqz0.png

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
All seems good on the sites ive just tested this on. Thank you.
