### ISSUE TITLE
SSS media does not order by "most recent" in List mode.

### ISSUE THREAD

**Issue by Glynnage** [superspeedyplugins/issue-tracker#44]
**Describe the bug**
Media library search results do not order by "most recent" when searching in List mode. This is not an issue in Grid mode

**To Reproduce**
1. Activate Super Speedy Search
2. Settings > Super Speedy Search > Main: Enable “Override Back-end Search Results”
3. Upload 3 images with same word in name
4. Check images are most recent, in list and grid
5. Results: 
List: https://i.imgur.com/iZxXfe3.png
Grid: https://i.imgur.com/kWXazhO.png
6. Search using repeated word
7. Results: 
List: https://i.imgur.com/6GF4pkQ.png
Grid: https://i.imgur.com/ORB93k5.png

**Expected behavior**
When searching in List mode, results should display the most recent results first.

**Comment by dhilditch** [comment]
Fixed in 4.38
