### ISSUE TITLE
SSF - Breaks Featured Products First Plugin

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#45]
**Describe the bug**
We are using Featured products first https://wordpress.org/plugins/featured-products-first-for-woocommerce/

All Wordpress product category pages should show the featured items at the top for optimising sales/conversions.

Since installing SSF the ordering no longer shows Featured items first.

Can we have a compatibility check for this OR a feature adding in SSF to allow featured items to be displayed first.

A feature would totally solve the problem and I would get rid of the Featured Products First Plugin.

**To Reproduce**
https://www.pinntecdirect.com/ - The items shown here as Pinntec Best Sellers are all marked as featured.
Example here
https://www.pinntecdirect.com/product/tech21-evo-clear-mobile-phone-case-17-cm-6-7-cover-transparent-11/
Viewing the containing archive - This item should appear first
https://www.pinntecdirect.com/product-category/computing-and-peripherals/mobile-phones-and-smartwatches/mobile-accessories/
Since putting SSF on the order no longer shows the featured items first.

**Expected behavior**
featured items should appear first on archive pages in the loop with all other products.

**Screenshots**
The feaured items have a featured flag. They are supposed to appear at the top of the archive pages.
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/f2293dd3-943d-424d-80cf-cf3745c3f252)
As you can see here the featured items are not first since using SSF.
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/261b5728-87bc-43a7-b7d3-acb1d121875a)

**Desktop (please complete the following information):**
All devices and browsers

**Additional context**
This is vital for marketing on huge stores.

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch
Changing the Scalability Pro option Remove Sort Options to "Keep Sort Options" solves the problem.

![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/9dab0067-80c2-4e60-acf2-8097b067e7ff)

This ensures that Featured products are loaded first.

Im not sure on the ideal speed solution here.

Can we get an option to show featured items first on archive pages? so the query is optimised?
Or
Can we get an optimised query for the Featured products first plugin?

Otherwise I'll just leave the keep sort options enabled.

**Comment by dhilditch** [comment]
This is by design. The Remove Sort Options option only operates on the main query but in this case, the Featured Products First plugin is adding an extra sort to the start.

**Comment by thinkjarvisdesignandmarketing** [comment]
Thanks Dave, Happy with this. Its working well on the sites I am using it on now and playing nicely with SSS, SSF and SPRO
