### ISSUE TITLE
External Images not showing image thumbnails in media > list view

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#46]
The grid view shows our images, but the list view does not.

https://i.imgur.com/m5GNnaY.png

1. Install external images
2. Create new post or product
3. Add a featured image from an external url using our external image meta box
4. Visit media > library
5. Change to list view

Image for item does not show in list view whereas it does in grid view.

Fix the list view.

**Comment by dhilditch** [comment]
This is an easier one to get started with @hmkayani  - when you view images in wp-admin > Media > Grid list, you'll see any external images thumbnails, but for some reason in list view the thumbnails don't appear.

Figure out why and fix.

**Comment by hmkayani** [comment]
This issue is not replicating any more with the latest code. Seems it got fixed
