### ISSUE TITLE
SSS reset button clears panel, but then clicking inside search box brings panel back

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#47]
1. Search for something using our search box - search results panel appears
2. Click the reset button X to the left of the search button - the search panel disappears
3. Click inside the search text box again - the search panel appears again with the previous results!

When reset is clicked, it's currently clearing the panel but then clicking inside the panel again is bringing that panel back. The reset should have cleared this.

Note there is separated intended functionality so that if a user searches for something but then clicks outside of the search panel then the search panel will hide, but then clicking back inside the search text box makes the search panel re-appear - this is the intended behaviour.

However, if the reset X button has been clicked, then the search panel history should have been wiped.

This is a javascript update required.

https://i.imgur.com/koOpeey.png

After clicking x, click back into the search box or click outside then back in the search box and the previous search re-appears.

Similarly, if I search something and then delete it then click outside then back in the search box, part of the search box re-appears.

https://i.imgur.com/0ItX8ba.png

Both of these bugs can probably be fixed with the same piece of JS so i've grouped them together.

**Comment by hmkayani** [comment]
This issue is fixed in branch "search-issue-fix" in version "4.39"

**Comment by dhilditch** [comment]
Fixed in 4.39, reset panel correctly clears search box.

**Comment by gfarma** [comment]
Nice fix!

I want to add something here:
When you type something at the search box and then click the search button, it drives you at the search results page.

At this page the 'x' button stills appears with the result, unclickable.

I propose:
1) do not display it, until someone clicks inside the bar and types a letter. then appear it normally

![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/b0eeb47c-dbee-49cc-9098-0cbb755e7ee7)

This happens at the search results page (at least at FSE)
