### ISSUE TITLE
SSS: Limit decimal places in Ajax dropdown results

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#5]
**Describe the bug**
When Prices are enabled in Ajax dropdown search results - The prices are displayed as they are uploaded whereas WooCommerce by default limits these to two decimal places.

Our data importer works out prices to about 6 decimal places - This means that in the Ajax dropdown prices are show with 6 decimal places.

**To Reproduce**
1. Super Speedy Search Installed
2. Create a product with a price that contains more than 2 decimal places
3.  Ensure ultra Ajax is enabled in SSS
4.  Search for the product
5.  Frown at the odd price formatting

**Expected behavior**
The prices shown in the SSS Ajax search AND the full results page should be to 2 decimal places regardless of how many decimals they are entered to.

**Desktop (please complete the following information):**
All browsers and devices

**Additional context**
Note I have asked WPALLIMPORT for some extra filtering on the price so it converts uploaded prices to 2 decimals. If you would like me to wait and see what they come back with happy to report back here.

**Comment by thinkjarvisdesignandmarketing** [comment]
WPALLIMPORT have provided this as a function so data is only imported to two decimal places. It would be good to have a filter in place to stop the results showing to more than 2 decimals without having to enter them to 2 decimals.

In WPALLIMPORT in the price field - Add the following.
[round({price[1]}, 2)]
You can use it in your import template like this: https://www.wpallimport.com/documentation/inline-php/. If that doesn't help, we need to see a few examples (before and after function) to advise you further.

**Comment by dhilditch** [comment]
Fixed in 4.33
