### ISSUE TITLE
SSS - Don't drop suggestions table if it already exists otherwise we dump existing suggestions

### ISSUE THREAD

**Issue by Glynnage** [superspeedyplugins/issue-tracker#50]
**Describe the bug**
Suggestions get removed from Settings > Super Speedy Search > Suggestions ONLY when table rebuilt through "Rebuild tables" button - manual rebuildl no problem. truncate table on wrong line
**To Reproduce**
1. Activate Super Speedy Search
2. Go to Settings > Super Speedy Search >Suggestions
3. Add suggestion in "Add Suggestions" 
4. Save
5. Rebuild table
6. Refresh and check Suggestions tab.

**Expected behavior**
Suggestion in "Add Suggestions" should still be there - disappeared

**Comment by dhilditch** [comment]
The fix in the end for this was to ensure the table rebuild button does not call the 'save settings' - this was happening and it was then somehow emptying the suggestions since they were not being passed through.
