### ISSUE TITLE
SSS - Alter [metavalues] form html to allow decimals

### ISSUE THREAD

**Issue by Glynnage** [superspeedyplugins/issue-tracker#51]

**Comment by dhilditch** [comment]
1. Visit Settings > SSS > Weights tab
2. In any of the numeric entries for the weight factors and numbers, enter a decimal value and hit save

What happens: https://i.imgur.com/hIiT4Ky.png

Expected: Decimals should be allowed to be stored here.

Note: This firstly involves altering the HTML to allow decimals in the form - this is HTML form validation that is happening.

Once you can successfully save, confirm that the decimals actually DO save (i.e. reload the page and confirm you can see decimals) - I can't remember what numeric type I have in the options - I think that part will be fine.

**Comment by hmkayani** [comment]
I have fixed this, now we can add decimal values in weights. It is available in version 4.40

**Comment by dhilditch** [comment]
HTML fixed in 4.40
