### ISSUE TITLE
Repeating main image in External Images

### ISSUE THREAD

**Issue by ozteeprint** [superspeedyplugins/issue-tracker#56]
I imported 1 product via WP-ALL IMPORT Plugin.  I used external_image_url for the images.  This product has 3 colors : Black, Red and White.  The default color is Black.

The link for the product : https://ozteeprint.com/product/a6-baseball-1

After I imported 1 product, I checked Media Library. Black color repeated 2 times and other color is repeated 1 time. There is no galley images.

<img width="496" alt="Screen Shot 2024-01-19 at 3 01 24 PM" src="https://github.com/superspeedyplugins/issue-tracker/assets/154464714/48dc4c5e-6615-4847-87cb-c0987e8e2ce4">

**Comment by ozteeprint** [comment]
Although I didn't import gallery images for this product via WP-ALL IMPORT, External Images Plugin received main black image and set it gallery images. Attached screenhot.  

<img width="254" alt="Screen Shot 2024-01-19 at 3 10 20 PM" src="https://github.com/superspeedyplugins/issue-tracker/assets/154464714/9478ff1e-318c-41df-bdad-3857655a183d">

**Comment by ozteeprint** [comment]
See the images of this product.
<img width="536" alt="Screen Shot 2024-01-19 at 3 14 54 PM" src="https://github.com/superspeedyplugins/issue-tracker/assets/154464714/3c0cd2eb-d3fb-43ef-8d9e-36b519313633">
<img width="537" alt="Screen Shot 2024-01-19 at 3 15 09 PM" src="https://github.com/superspeedyplugins/issue-tracker/assets/154464714/72f0c338-cc02-40f7-881d-dad0df6ba94a">
<img width="525" alt="Screen Shot 2024-01-19 at 3 15 27 PM" src="https://github.com/superspeedyplugins/issue-tracker/assets/154464714/8231987a-8e9f-4cc5-98f9-3d981939c4c7">

**Comment by dhilditch** [comment]
1. I need to log on and check what setting oztee has in their wp-config.php for using featured images in the gallery
2. Get a retest with the definition entry changed to not use the featured image in the gallery
3. Repeat the test oztee ran on local - import a single product with 3 variations, no gallery, just a featured image for the main product + each variation - technically under the hood this IS 4 products, so 4 images, but the same image should not be repeated in the gallery

**Comment by dhilditch** [comment]
https://i.imgur.com/gifovd5.png - looks like somehow there's a bug with the EI_ADD_FEATURED_IMAGE_TO_GALLERY definition.

This is set to false in the plugin, and they do not set it true on ozteeprint, so the featured image should not be getting added to the gallery.

Need to look through the code and search for EI_ADD_FEATURED_IMAGE_TO_GALLERY and find out why this setting is not being used properly - it looks like this is being treated as true all the time.

**Comment by ozteeprint** [comment]
EI_ADD_FEATURED_IMAGE_TO_GALLERY I had to comment this code because main black image attached each other color on the front end.  I sent screenshots. This part was fixed after I commented this code.

![image](https://github.com/superspeedyplugins/issue-tracker/assets/154464714/6b481505-7e64-4fcf-82fe-abdb87488c5e)

**Comment by dhilditch** [comment]
This issue can be closed - original issue was from user having those defines in their wp-config.php and I have explained how main products featured image and specific variation images can be different and need their own attachment entries.
