### ISSUE TITLE
YIth wishlist issue for for infinity load 

### ISSUE THREAD

**Issue by Starfiniti** [superspeedyplugins/issue-tracker#58]
Hello,

Video of the issue - https://www.loom.com/share/66e714e08101452ba540130344635d49

The plugin I'm using - https://yithemes.com/themes/plugins/yith-woocommerce-wishlist/

Best Regards

**Comment by hmkayani** [comment]
Awaiting for customer feedback to replicate the issue

**Comment by Starfiniti** [comment]
Wait. What exactly do I need to do?

**Comment by hmkayani** [comment]
Check video

https://www.loom.com/share/cac7be08033d4bc5a9b3bd11c7c2b5f5?sid=1d18884a-638d-4fff-8900-42b9198372d4

may be its customer specific issue...

**Comment by dhilditch** [comment]
Closing this as neither of us could replicate it. It's possible some JS optimisation program was interfering with the JS
