### ISSUE TITLE
Fix the option in Super Speedy Search to let users choose what to search (title, content, excerpt, meta, taxonomies)

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#59]
https://i.imgur.com/ffnOP20.png

This option is currently ignored. The only way to actually currently change search to only search in the title is to enable one of the definitions from the defines.php file and add that to your wp-config.php.

The issue underneath the hood is that in the past, I used to create all the various combinations of fulltext index required here e.g:

post_title
post_title, post_content
post_title, post_excerpt
post_title, post_content, post_excerpt

However, since then there are now an additional 2 columns which get index - meta_values and tax_descriptions so if we created all of these indexes it would use up a LOT of storage.

1. Update the setting to include 2 extra checkboxes to let users choose to search meta values and taxonomy titles+descriptions - all of these should be default enabled for new users
2. Alter the build process so that it reads from this setting and chooses the correct index to create. To alter the build process, you can alter the function which returns all of the SQL statements to perform the build/rebuild. In here you will see currently it creates an index on post_title and post_title, post_excerpt, post_content, meta_values, tax_descriptions. This should be changed to just create the correct index based on the description.
3. Add an extra SQL statement after wp_superspeedysearch_xyz is renamed to wp_superspeedysearch to update/create a new option in wp_options against the key 'sss_search_columns'.
4. On Settings > Super Speedy Search > Main tab - https://i.imgur.com/8qmUtjm.png - compare the setting stored/updated as part of the build process (sss_search_columns) to the setting with the checkboxes - if these are different, then show an X: Searchable columns different from fulltext index on table - rebuild required.  If they are the same, show a tickmark with the text: Fulltext index ready
5. Alter sss.php to pull the searchable columns from sss_search_columns and adjust the search accordingly. Currently you'll see it's creating an array of 5 items and just always searches all 5 columns. If the stting

Basically - the whole thing here is that if someone changes the option in the settings page we cannot change the search to match that yet because if we do a DB error will occur. Instead, we must notify the user that a table rebuild is required to create that index for their new setting choice. This is why we need to take this column selection from the setting which you will update in the build process.

You'll need to test this afterwards and I'm expecting e.g:

1. When someone changes the setting for which of the 5 things to search, a warning X should appear at the top section of the Main tab informing the admin tha a table rebuild is required
2. After this setting has been changed, the front end search will not be altered yet to reflect the new setting, i.e searches will continue to use the previous setting until the rebuild runs - you can use Query Monitor to check this, click the Database Queries tab and search for the word 'AGAINST' to find the fulltext search
3. Once a rebuild has run, there should be a CHECKMARK on the Main tab  and the front-end search should be updated to reflect the new setting.
Any questions, just ask

**Comment by hmkayani** [comment]
Now when the user select either Meta Value or Taxonmy and click save, a message "Searchable columns different from fulltext index on table - rebuild required" is displayed on the Top of main Tab. And when we rebuild tables, it get indexed and searchable. Code is merged in 4.40

**Comment by dhilditch** [comment]
Columns to search now properly works. Table rebuild required if columns altered.

I need to fix further - developer mistakenly put update_option inside PHP which means if users run manual table build or rebuild then the table columns with indexes built will not be referenced.

https://i.imgur.com/LeLR0Fm.png

**Comment by dhilditch** [comment]
Fixed in 4.41
