### ISSUE TITLE
Compatibility: SSS issue - Search results when signed in are different/more accurate than when signed out

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#6]
**Describe the bug**
Enfold with SSS enabled:

Example site:
URL https://www.pinntecdirect.com/

SSS replaces the enfold default search and also the woocommerce default search.

https://www.pinntecdirect.com/?s=laptop serves the right results MATCHING ULTRA AJAX RESULTS but displays them as a list not a product grid - (Enfolds default search results page looks pants so I want to always use the product post type below:)

https://www.pinntecdirect.com/?s=laptop&post_type=product serves the wrong results but displays them in a product grid. Therefore SSS is not overriding Enfolds product search correctly.

How can I stop Enfolds/WooCommerce &post_type=product search loops preventing Super Speedy Search results from not showing on the page?

I want to display the search results in a product grid as the search overrides only include products.

**To Reproduce**
1. I can provide you with a pre-configured test environment. Please advise
2. Install Wordpress, Woocommerce, Enfold, SSS
3. Enable Ultra Ajax and set PRODUCT as the default post type and as the only posts to be shown in search results
4. Try doing a search using the two perameters shown above to see the issue
5. The results shown are different but they are supposed to match eachother.

**Expected behavior**
With all of the overrides in place the Ultra Ajax results, ?s=term and ?s=term&post_type=product should show the same search results.

**Screenshots**
Please use the links above from client site for example.

**Desktop (please complete the following information):**
All devices and browsers

**Additional context**
I have raised a ticket with Enfold but I think this might be a SSS issue to resolve as it appears to be a compatibility problem.
https://kriesi.at/support/topic/bug-search-results-pages-not-overriding-correctly-urgent/

**Comment by thinkjarvisdesignandmarketing** [comment]
Following on from this - I cannot tell which search results are correct as per super speedy plugins and which are wrong.

I had assumed that the Ajax results were the ones from SSS this is probably the first thing I need your help confirming. As the results shown in Ajax are the ones that I ideally want to appear in the search results page.

**Comment by thinkjarvisdesignandmarketing** [comment]
Ok further test - Disabled SSS - The results shown on the product search results page are generated by the default Wordpress/woocommerce search NOT SSS.

So SSS is not overriding the search results page correctly.

Please can you assist?

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
OK so I checked again - Signed out users are getting a different set of results to signed in users. So when logged in as ADMIN the results shown in the ajax are different to the results shown in ajax when signed out.

The results when signed in as an admin seem more relevant than those seen when signed out.

**Comment by thinkjarvisdesignandmarketing** [comment]
I can provide login details to the site if you need them so you can see the two ajax search results signed in vs signed out. Drop me a DM on Discord if you want them.

**Comment by dhilditch** [comment]
Hi - I cannot replicate this on my local environment.

Can you please follow the guide here to figure out why SSS is not replacing your search?

https://www.superspeedyplugins.com/kb/super-speedy-search/faq-super-speedy-search-2/how-to-check-if-super-speedy-search-is-working/

If you still struggle, please contact me on Discord and you can DM me credentials directly there rather than here in Github. Then if there is a bug, you can re-open one with repro steps.

**Comment by thinkjarvisdesignandmarketing** [comment]
I'll dm you login details so you can see what I mean.

I'm not sure which of the two searches is sss and which isn't or whether one is using an admin search and one isn't.

The results signed in appear much better than the signed out results. It's really bizarre.
