### ISSUE TITLE
SSS | Add weights for short LIKE-based tokens

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#62]
**Is your feature request related to a problem? Please describe.**
In some cases the default 3 letters that the fulltext search begins is not working as exprected, beacause I cannot search for a product that has this name for example 'Musa 02' because '02' has 2 letters and it doesn't include it at the results like below:
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/87cfba7d-a653-47a0-81ec-c9c6b37808fa)

**Describe the solution you'd like**
 I would like to choose at how many letters the fulltext search should begin. In my case 2 letters.

**Comment by gfarma** [comment]
Do the same at taxonomies searches 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/248ffef8-e1f6-4cb7-8673-d1a153cfbb88)

In this case I would like to increase the letters at 3 or 4 because when you type 1 letter it displays a lot of results like here: 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/38164d5c-23ae-455b-a73e-405ddebf55d3)

**Comment by dhilditch** [comment]
Had another report from a customer for searches like IPHONE 15

They are thinking it is not finding the product, but it's actually the weights are not present for the short tokens < 3 characters.

* Update the weighting SELECT query if there are any LIKE statements to add weight for the LIKE token matches.

What we expect - searching for MUSA 02 or IPHONE 15 should always be showing IPHONE 15 above IPHONE 14 etc

**Comment by RexHavoc69** [comment]
We have customers trying to search for things like 'M.2' but the results seem random at best.
https://pp.co.nz/?s=m.2&post_type=product 
When I searched this just now I got a warning in Query Monitor...
Warning | Invalid argument supplied for foreach() 

    wp-content/plugins/super-speedy-search/includes/sss.php:298
    SSS::getSearchSQL()
    wp-content/plugins/super-speedy-search/includes/sss.php:838
    SSS->sss_pre_get_posts()
    wp-includes/class-wp-hook.php:324
    do_action_ref_array('pre_get_posts')
    wp-includes/class-wp-query.php:1881
    WP_Query->get_posts()
    wp-includes/class-wp-query.php:3824
    WP_Query->query()
    wp-includes/class-wp.php:696
    WP->query_posts()
    wp-includes/class-wp.php:816
    WP->main()
    wp-includes/functions.php:1336
    wp()
    wp-blog-header.php:16
    
    Plugin: super-speedy-search

**Comment by dhilditch** [comment]
Fixed in 4.47
