### ISSUE TITLE
Admin bar assistance for Super Speedy Search on search results pages

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#68]
If an admin is using the site and they are on a search results page (front or back), a Super Speedy Search bar should be added to the wp-admin bar.

1. Clickable option to show RELEVANCE (reload with ?showweights=1)
2. Warning if Super Speedy Search not active for this search
3. Warning if other plugins are performing additional LIKE based searches outside of our searches
4. Link to get help with these search results from our KB

And in particular, I want to also double check that the SELECT MATCH AGAINST WITH BOOLEAN on the SELECT is giving proper weights. I thought I'd changed that to not use BOOLEAN in the SELECT specifically to improve the weighting system.

**Comment by dhilditch** [comment]
re: the weights using BOOLEAN vs not using BOOLEAN mode in the SELECT statement, I just want you to report back to me what you find in any differences in the weights when you use one vs the other.

The aim here is to add an admin panel to ANY page, front AND back (wp-admin) which performs a search and primarily to inform the user whether SSS is enabled for this search.

https://i.imgur.com/5lDewNu.png

e.g. in that area above, but not with a white background, just with normal background colour. There should be a little alarm bell alert next to SSS if SSS is not active on this search results page.

Then hovering over it, show the 'View Weights/Relevance' option, SSS NOT ACTIVE/ACTIVE, KB link.

**Comment by hmkayani** [comment]
This issue is fixed in version 4.45

**Comment by hmkayani** [comment]
Changes are made in read me file under v 4.50

**Comment by dhilditch** [comment]
Confirmed fixed in 4.50
