### ISSUE TITLE
One widget area for all devices

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#7]
At the moment we have two widget areas for filters.

I will share my possible solution to this once I have finished coding it. one of the client sites I inherited already has a clever show/hide system for widgets. preventing the need to have two widget areas - one for mobile and one for desktop.

This makes having hundreds of filters easier to manage - One set of filters that shows and hides on all devices rather than two widget areas.

Technically this is possible in a round about way at the moment by using the widget area shortcode in both the default widget sidebar area and the header widget area. But what I am suggesting will make it so it natively uses the same set of options in both locations.

Will update once I have extracted the code.

Essentially this should reduce the amount of code loaded because the filters are loaded once rather than in two locations on the same page.

**Comment by dhilditch** [comment]
There already is one widget area for all devices. If your theme is in fact using two separate widget areas then that's not a great design by your theme.

I don't see any actionable item here so I'm closing as unplanned. We can chat more about this on Discord if needed and I can draw up a KB article to help.

**Comment by thinkjarvisdesignandmarketing** [comment]
OK probably not explained this well.

Enfold sidebar disappears on mobiles. So natively you cannot use it on mobiles.

I would normally add the filters into a widget area above the shop that only shows on mobiles to get filters to show on small devices. Therefore two sets of the same filters set up in two widgets. Desktop and mobile.

But I do have some code on one site that adds a button to display the widget area as an overlay on mobiles. So I'll probably go with something like that.

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
I can confirm this is an issue with Enfold. By default the sidebar hides on mobiles.
I have created a simple JS button combined with CSS that solves the problem - Allowing the same widget area on all devices.

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
I have created a solution using a JS button to show and hide the sidebar on mobiles.
Details here if anyone else finds this thread and uses Enfold:
https://github.com/KriesiMedia/Enfold-Feature-Requests/issues/89
