### ISSUE TITLE
SSF | try to add interactivity api, not only plain ajax

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#72]
I think interactivity api will make ssf next level:

https://make.wordpress.org/core/2023/03/30/proposal-the-interactivity-api-a-better-developer-experience-in-building-interactive-blocks/

https://developer-wordpress-org.translate.goog/block-editor/reference-guides/packages/packages-interactivity/?_x_tr_sl=en&_x_tr_tl=el&_x_tr_hl=el&_x_tr_pto=sc

**Comment by gfarma** [comment]
Issue from woo-blocks https://github.com/woocommerce/woocommerce/issues/42255

**Comment by dhilditch** [comment]
This is being rolled up into our gutenberg upgrade project, however we have referenced this issue from our docs, so @gfarma if you have any specifics about which blocks you think would benefit from talking to each other then please submit the ideas.

Our main aim with the gutenberg upgrade is to make the blocks available obviously, still have old-school widgets for backwards compatibility, have the blocks fully ajaxed but fast (using the rest api or our ultra ajax) and then also have JS able to construct the destination filter URLs so we can have the 'apply' button building the URLs from the front-end.
