### ISSUE TITLE
SSS | Change priority on search results page when a taxonomy is displayed as suggested

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#76]
You can add a checkbox backend to do the below:

![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/93576153-252d-49af-9388-0f147f68023d)
when user types convex and hit search or enter instead of displaying the products, diplay automatically the first result of the taxonomy 'Convex' brand page in this case instead of products that match criterias 

For example here it should open this page: https://fshome.gr/brand/convex/

I think this feaure with caution would be very nice UX

**Comment by dhilditch** [comment]
This has been rolled up into our larger piece of work to overhaul the search widget and make it awesome
