### ISSUE TITLE
SSF | Hide/disable this filter for spesific categories (taxonomies)

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#77]
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/49fe1f18-5ec6-40e5-b8e5-6e8be05e2f9f)

Can you do the same for taxonomies, product-cat etc?

**Comment by dhilditch** [comment]
@gfarma https://i.imgur.com/bgNHdW4.png this is already how this part operates.

The box will take taxonomy names - e.g. product_cat - and then the widget will be hidden until a product category is selected.

I'm aware this is not the full amount of config people want, but then there are other plugins out there which can take on this work like the fantatistic and totally free Widget Context plugin https://wordpress.org/plugins/widget-context/

Maybe the feature request here is to add some recommended plugins on a recommended plugin installation page when users activate SSF?

**Comment by dhilditch** [comment]
Feature Request could be to add this dependency library: https://github.com/afragen/wp-dependency-installer

And then to add Widget Context as a recommended plugin along with ideally a description of how this plugin will benefit SSF.

**Comment by gfarma** [comment]
So at this category: https://staging.fshome.gr/category/plakakia/ we just add this: 

![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/74eb826d-b2cc-4818-a350-58b056379f60)

?

**Comment by voodoo911** [comment]
As we discussed via DM - option you sent to show/hide widget based on other widget selected or not. There is no option to show/hide widget based on category you are currently in. Only based on filters

**Comment by gfarma** [comment]
Ok I used  https://wordpress.org/plugins/widget-context/ and works great.

Yes add it as a recommended plugin

**Comment by dhilditch** [comment]
Closed, won't fix, will add Widget Context as recommended plugin instead.
