### ISSUE TITLE
SSF | Post meta range should not accept empty values

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#79]
If you click the button to apply here, without entering any value at the box
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/e49e785a-7ca8-44b0-81a7-d2b6f54fe732)

it searches for empty values. I think the apply should be un clickable until the user inputs a letter at one of the min or max boxes.
https://staging.fshome.gr/brand/agb/

**Comment by voodoo911** [comment]
Version 5.19 Patch added for both min max empty issue

**Comment by voodoo911** [comment]
Reason of issue was old js file, all fine now

**Comment by gfarma** [comment]
One small addition I propose is to don't let the user input values bigger at the left input box than the right one.

![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/82f0e915-e9ae-42ef-a638-14762b6d848a)

in case he does the apply should display a notice like: 'The range is not correct' or 'You cannot input a bigger value at the first box' . And not make the query because is something that cannot work
