### ISSUE TITLE
Exact phrase search not working in Super Speedy Search

### ISSUE THREAD

**Issue by RexHavoc69** [superspeedyplugins/issue-tracker#83]
If I search within quotation marks for '"4070 Super"' I get results of any product with the string '4070' and 'Super'.
I should only get results for products that contain the exact phrase '4070 Super'

from https://github.com/superspeedyplugins/issue-tracker/issues/37 as it was marked as completed.

**Comment by gfarma** [comment]
Something similar here: 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/c0ef489e-498b-4b6d-903f-c0e435180195)


I have this config:
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/579a47f4-58e2-4ac4-872a-15ade5950bcf)

When I search for 'χρωμιο' it returns product that don't have this keyword in title.
https://staging.fshome.gr

**Comment by gfarma** [comment]
1) SSS Version 4.44
2) 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/7be29def-f600-495f-a749-e97b344cd041)

3) I tried both options but still the same
