### ISSUE TITLE
Toggle button for in/out of stock

### ISSUE THREAD

**Issue by JohnnyHansens** [superspeedyplugins/issue-tracker#84]
We have products that should be possible to search and view even if not in stock.

We would however like to give the customer that is looking for a product in stock the ability to filter the search results and product categegory products so that only in product in stock show.

I think the cleanest option would be a simple toggle switch: "in stock"

**Comment by Glynnage** [comment]
Here is a doc for it. Its a separate widget called "Super Speedy Stock Status" and has a toggle option. 

https://www.superspeedyplugins.com/kb/super-speedy-filters/features/widgets/products-in-stock-filter/

**Comment by dhilditch** [comment]
We just realised you're asking for Super Speedy Search?

We have this option in Super Speedy Filters for a toggle that you can place where you wish.

In Super Speedy Search, the rule is as follows now in the recent update:

1. If SSF installed, use the stock setting from the SSF > Main tab > Stock control - either show or hide in stock or out of stock items
2. If SSF not installed, use the stock setting from WooCommerce - either show or hide in stock or out of stock items.
3. If show all is selected (my preference for search), then there is a default weight added to give more relevance to items which are in stock, so if someone searches for 'red socks' then out of stock red socks would not appear in the list if there were enough red socks that are in stock to fill up your search results.

So - given all this, does this help at all or do you still want some kind of widget added?

We've realised maybe you mean a widget actually inside the search box itself?

If you could add an image that would be helpful and some more explanation.

**Comment by dhilditch** [comment]
This is being rolled up into our front-end search widget overhaul
