### ISSUE TITLE
SSF | Active filters don't have a design to be shown as active when you select display type: image label etc

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#86]
here https://staging.fshome.gr/category/pomola/pomola-portas/pomola-portas-me-rozeta/?pa_finish-color=415 
this filter has been selected: 

![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/ed860180-650c-44ff-bc54-dd07adfb4caa)

But there isn't any design bold letter (or something) to make it clear.

the active filter design exists only in: image large (bold), image list (bold)

**Comment by dhilditch** [comment]
Confirmed fixed in 5.30
