### ISSUE TITLE
Greenshift Breadcrumb on the product custom taxonomy page shows the wrong URL when SSF permalink rewrite is ON

### ISSUE THREAD

**Issue by TempoRoyale** [superspeedyplugins/issue-tracker#87]
**Describe the bug**
Greenshift Breadcrumb on the product custom taxonomy page shows the wrong URL when SSF permalink rewrite is ON

**To Reproduce**
1. Create custom taxonomy for woocommerce product. Add terms in the taxonomy. Example: Taxonomy = Style, Terms = Abstract.
2. Assign a few products to the taxonomy term.
3. Create Kadence elements. Add Greenshift Breadcrumb Block. Set Hook = "replace above content hero". Apply the kadence element to the taxonomy archive page.
4. Set the SSF "enable permalink rewrite" to ON
5. View the custom taxonomy term page (i.e. Abstract) and see the Greenshift Breadcrumb show the "first product" URL and title instead of the taxonomy term URL and title.

**Expected behavior**
Greenshift breadcrumb will show "the first product in the page" URL and title instead of the taxonomy term URL and title.

**Screenshots**
![image](https://github.com/superspeedyplugins/issue-tracker/assets/17023149/21732d29-5974-4a57-9ca4-a719b97e3c8c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge, Chrome

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 16.7.5
 - Browser: Safari, Chrome, Edge

**Comment by dhilditch** [comment]
Fixed in 5.21 which should be released tomorrow. Note: You will need to disable the two options in Advanced tab (everything else should still work with those disabled with 5.21)

https://i.imgur.com/zPVRqz0.png
