### ISSUE TITLE
SSF needs a new button to delete all SSF tables and reset the settings and clear the options

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#88]
Obviously this should only affect any tables created by Super Speedy Filters and any options created by SSF.

1. Add DELETE ALL DATA button in RED and in CAPS on the advanced tab
2. Clicking it should then ask the user to type the word DELETE into a box to confirm this deletion
3. Then delete the tables that get created in the object ancestors build process
4. Then delete the options fww_settings and any other options we have created

**Comment by voodoo911** [comment]
Functionality added to v 5.21

**Comment by henrik-smith** [comment]
Is see it says functionality added to v 5.21, but I still can't see it. Not in v 5.21 or 5.22. Was it missed, or am I missing something?

**Comment by dhilditch** [comment]
Functionality added in 5.30 - in latest dev version - merge completed, testing completed, deployment will be soon.
