### ISSUE TITLE
Add button to SSS Settings Advanced tab to let users delete data

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#89]
Obviously this should only affect any tables created by Super Speedy Search and any options created by SSS.

1. Add DELETE ALL DATA WHEN PLUGIN DEACTIVATED button in RED and in CAPS on the advanced tab
2. Clicking it should then ask the user to type the word DELETE into a box to confirm enabling this checkbox
3. Then add a deactivation hook for the plugin which checks if this option is enabled to delete all data
3a. delete the tables that get created in the build process - wp_superspeedysearch etc, tokens etc
4a. delete the options sss_settings (pretty sure that's its name) and any other options we have created

**Comment by dhilditch** [comment]
I updated the bug above because I am fairly certain that when admins move to another page on wp-admin, SSS will create some default settings for the admin.

So instead we need to have a checkbox for admins to choose to delete all data when the plugin is deactivated and then have a deactivation hook.

**Comment by hmkayani** [comment]
This is now implemented, in branch "Search-issue-fix" and readme updated with 4.46 version

**Comment by dhilditch** [comment]
This looks great
