### ISSUE TITLE
Strict Search not working

### ISSUE THREAD

**Issue by RexHavoc69** [superspeedyplugins/issue-tracker#9]
**Describe the bug**
Super Speedy Search

Strict Search not working. Results are as if 'Match any words' is selected.

**To Reproduce**
1. Go to https://pp.co.nz/?s=Asus+Router&post_type=product
Most of the result pages do not have the word 'router' listed.

**Expected behavior**
Only products with the words Asus & Router should show in the results.

**Screenshots**
![image](https://github.com/superspeedyplugins/issue-tracker/assets/92769963/1da4a3a9-6756-4ec1-add7-77452179105b)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Comment by RexHavoc69** [comment]
This issue seems to be related to a synonym. I had a synonym Router <> Modem. Once this was deleted, the expected result set was observed. However, this identifies a synonym issue because the results did not have the word modem or router included.

**Comment by dhilditch** [comment]
This is related to our Synonyms code. There is a function called getSearchSQL in sss.php which returns various arrays configuring how the search should proceed.

Currently, if a user has entered synonyms, we change a strict search to a soft search, but that means other items can be returned when we do not want them to be.

e.g. the above example, Asus Router is searching against (+asus* router* modem*) and then matching everything from asus whether the router or modem are there at all.

In the getSearchSQL function, there is an array called $exact_searches - IN ADDITION to router* and modem* being in the fulltext index search, if you add router and modem to the $exact_searches array it should ensure that one of those exists.

Please try implementing this and create reproduction environment where you can test and confirm this exact search is working properly, i.e. in this example, create an Asus product which doesn't mention modem or router and another which does mention 1 of them and another which mentionds both and then confirm the search results are working.

It may be the case we need to create a separate synonyms array in this search sql and update the places where this function is called to handle the 2nd pass of the query.

The query part is complicated, but I can help you with that if needed.

**Comment by dhilditch** [comment]
This issue fixed in 4.36
