### ISSUE TITLE
Recommended Plugins for SSF

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#92]
SSF does not work well with the new gutenberg widget editor. It also heavily relies on the redis object cache.

Find the best and latest library to use to recommend plugins to users and recommend both these plugins:

* Classic Widgets https://wordpress.org/plugins/classic-widgets/
* Redis Object Cache https://wordpress.org/plugins/redis-cache/

**Comment by voodoo911** [comment]
@dhilditch Not sure I get task - what you mean with recommend plugin to users? Like show admin notice in backend to show recommendation message like - you need to use those plugins for optimal fit?

**Comment by dhilditch** [comment]
I can do the research for you and tell you which library to use?

There are a couple as I understand it, one of them hasn't been updated on github for a while.

Basically, when people install SSF, we want them to see the recommended plugins coming from that library which then provides a way to auto install them or install them one by one.

**Comment by dhilditch** [comment]
https://github.com/afragen/wp-dependency-installer

**Comment by dhilditch** [comment]
Confirmed added and working well in 5.30
