### ISSUE TITLE
SSF upgraded users reported error undefined array key backorderstock

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#95]
super-speedy-filters.php:4456

Please ensure that in future, any new array keys that get added to the settings also get initialised. There is already some code attached to the init hook which checks if any settings are not set and if they are not it sets them, then it compares the options before & after and updates the options if they changed.

In that area is where you should be added new array keys so that these errors do not happen again in future.

https://imgur.com/ilueQxn

https://discord.com/channels/837258064704438282/877862826528620554/1211984055525048390

**Comment by voodoo911** [comment]
Code rebuilt to init variable via default hooks and ajax
