### ISSUE TITLE
SSF SEO indexable archive pages feature

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#96]
On the SEO tab, at the top, I want users to be able to see how many indexable archive pages they will have with their current settings.

https://i.imgur.com/t9zfJph.png

The important figures to count at the moment are:

* Maximum terms in canonical URL
* Maximum Indexable Taxonomies
* Maximum Indexable Terms
* Per Taxonomy Max Terms in Canonical URL/Max Terms Indexable - these should typically be set to the same number, typically set to 1
* Per URL parameter Max Terms in Canonical URL/Max terms indexable - typically set the same, and defaulted to 0 (You can find this on the URL structure tab)

Then a note underneath telling users that this page count does not include paginated pages and it does not subtract pages eliminated from indexing by the Minimum products required to index option.

Then the calculation is basically this:

Per Taxonomy, count the terms, if they have max canonical/max terms > 1 and global > 1, e.g. 2, then it would be: Total Terms * (total terms - 1). For most users, they should have the max terms per taxonomy set to 1. https://i.imgur.com/LR6Yxfj.png

So if they have max terms per taxonomy set to 1 (which is the default) then count the terms.

Then if they have 'Maximum Indexable Taxonomies' set to 1 - then the count is quite simple - it's just the total of all the terms.

e.g. if they have 1000 product categories and then have 100 brands and 10 colours and these are all archivable taxonomies and they have Max 1 set for everything then the total count would be 1000+100+10.

However, MANY people set the Maximum Indexable Taxonomies to 2 which means that URLs like:

/product-category/sneakers/brand/adidas/ become indexable.

In this case, using this example, the count would become:

1000 + 100 + 10 + (1000 * 100) + (1000 * 10) + (100 * 10) 

That would mean 1000 * 100 is 1 product cat combined with 1 brand, 1000*10 would be 1000 categories combined with 10 colours etc.

Store this result in the object cache and provide a little recount button which wipes the object cache through ajax and performs the count again. There are WordPress functions to count the terms, but it would be probably be more efficient to count the terms against my object ancestors table. For Debug purposes, I want to be able to compare these two counts. So when you count, can you count with 2 different sources of data?

1. Perform the count based on wp_count_terms function
2. Perform the count a second time based on wp_fww_objectancestors direct SQL count

Then have the ajax function print these out to the console with JavaScript and have it display the count based on wp_count_terms for now.

We are going to link from this section to an SEO article explaining to them how to configure their URL structure at the start.

`$term_count = wp_count_terms($taxonomy, array('hide_empty' => true) );`

**Comment by voodoo911** [comment]
@dhilditch I'm bit confused with your description. What will be final output of that ? Single number? Or it should list results per each taxonomy ?

Also:
Maximum terms in canonical URL
Maximum Indexable Taxonomies
Maximum Indexable Terms
Per Taxonomy Max Terms in Canonical URL/Max Terms Indexable - these should typically be set to the same number, typically set to 1
Per URL parameter Max Terms in Canonical URL/Max terms indexable - typically set the same, and defaulted to 0 (You can find this on the URL structure tab)

So :
Maximum terms in canonical URL
Maximum Indexable Taxonomies
Maximum Indexable Terms
== those are used in calculations

Per Taxonomy Max Terms in Canonical URL/Max Terms Indexable - these should typically be set to the same number, typically set to 1
Per URL parameter Max Terms in Canonical URL/Max terms indexable - typically set the same, and defaulted to 0 (You can find this on the URL structure tab)
== we use those settings, in case they are different from 
Maximum terms in canonical URL
Maximum Indexable Terms
?

Just need to clear that to get all calculations.

As for example that confuse:
"Per Taxonomy, count the terms, if they have max canonical/max terms > 1 and global > 1, e.g. 2" but we use only single value for paramteer? E.g. if  "Maximum terms in canonical URL" global is 2, but single is 1 - we use 1 ?

**Comment by dhilditch** [comment]
@voodoo911 I honestly do not understand how you can be confused. Go look at the SEO tab in SSF and you'll get some clarity and re-read my description.

The output will be a SINGLE NUMBER. If you want to be fancy, you can show people how you calculated the total. People would find that interesting and useful.

**Comment by dhilditch** [comment]
> As for example that confuse: Per Taxonomy, count the terms, if they have max canonical/max terms > 1 and global > 1, e.g. 2" but we use only single value for paramteer? E.g. if "Maximum terms in canonical URL" global is 2, but single is 1 - we use 1 ?

If you look at the SSF settings pages, this will become clear.

If you follow my original bug, this will become clear.

There are GLOBAL settings on the SEO tab and there are PER TAXONOMY settings on the URL tab. Is that your confusion?

**Comment by voodoo911** [comment]
Functionality added

**Comment by dhilditch** [comment]
Added in 5.33
