### ISSUE TITLE
SSF Advanced Widget options to limit number of results to initially shown should never be negative

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#99]
One customer entered -3 into the amount of items to fetch for ajax in SSF.

Change this to have a minimum of 0. The plugin checks for the value 0 - if it's 0, it loads everything.

Only need to change this through HTML.

https://imgur.com/mkCKVxr

**Comment by voodoo911** [comment]
Patch added

**Comment by dhilditch** [comment]
Fixed in 5.30
